/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-cottage-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ct1_img0 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/ODAY_result.webp";
import ct1_img1 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/2 copy_result.webp";
import ct1_img2 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/4 copy_result.webp";
import ct1_img3 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/5 copy_result.webp";
import ct1_img4 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/6 copy_result.webp";
import ct1_img5 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/7 copy_result.webp";
import ct1_img6 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/8 copy_result.webp";
import ct1_img7 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/9 copy_result.webp";
import ct1_img8 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/10 copy_result.webp";
import ct1_img9 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/11 copy_result.webp";
import ct1_img10 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/12 copy_result.webp";

export const images: StaticImageData[] = [ct1_img0, ct1_img1, ct1_img2, ct1_img3, ct1_img4, ct1_img5, ct1_img6, ct1_img7, ct1_img8, ct1_img9, ct1_img10];
