/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-cottage-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ct3_img0 from "@/imgs/Exterior/Cottage/majed cottage 37/oday_result.webp";
import ct3_img1 from "@/imgs/Exterior/Cottage/majed cottage 37/2_result.webp";
import ct3_img2 from "@/imgs/Exterior/Cottage/majed cottage 37/3_result.webp";
import ct3_img3 from "@/imgs/Exterior/Cottage/majed cottage 37/4_result.webp";
import ct3_img4 from "@/imgs/Exterior/Cottage/majed cottage 37/5_result.webp";
import ct3_img5 from "@/imgs/Exterior/Cottage/majed cottage 37/7_result.webp";
import ct3_img6 from "@/imgs/Exterior/Cottage/majed cottage 37/8_result.webp";
import ct3_img7 from "@/imgs/Exterior/Cottage/majed cottage 37/9_result.webp";
import ct3_img8 from "@/imgs/Exterior/Cottage/majed cottage 37/12_result.webp";
import ct3_img9 from "@/imgs/Exterior/Cottage/majed cottage 37/13_result.webp";
import ct3_img10 from "@/imgs/Exterior/Cottage/majed cottage 37/14_result.webp";
import ct3_img11 from "@/imgs/Exterior/Cottage/majed cottage 37/16_result.webp";

export const images: StaticImageData[] = [ct3_img0, ct3_img1, ct3_img2, ct3_img3, ct3_img4, ct3_img5, ct3_img6, ct3_img7, ct3_img8, ct3_img9, ct3_img10, ct3_img11];
