/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-cottage-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ct0_img0 from "@/imgs/Exterior/Cottage/amer abu hamdieh 5/ODAY_result.webp";
import ct0_img1 from "@/imgs/Exterior/Cottage/amer abu hamdieh 5/1_result.webp";
import ct0_img2 from "@/imgs/Exterior/Cottage/amer abu hamdieh 5/3_result.webp";
import ct0_img3 from "@/imgs/Exterior/Cottage/amer abu hamdieh 5/5_result.webp";

export const images: StaticImageData[] = [ct0_img0, ct0_img1, ct0_img2, ct0_img3];
