/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-cottage-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ct2_img0 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/oday_result.webp";
import ct2_img1 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-2_result.webp";
import ct2_img2 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-3_result.webp";
import ct2_img3 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-4_result.webp";
import ct2_img4 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-5_result.webp";
import ct2_img5 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-6_result.webp";
import ct2_img6 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-7_result.webp";

export const images: StaticImageData[] = [ct2_img0, ct2_img1, ct2_img2, ct2_img3, ct2_img4, ct2_img5, ct2_img6];
