/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in0_img0 from "@/imgs/Interior/جمعية عطاء 62/oday_result.webp";
import in0_img1 from "@/imgs/Interior/جمعية عطاء 62/Untitled-1_result.webp";
import in0_img2 from "@/imgs/Interior/جمعية عطاء 62/Untitled-2_result.webp";
import in0_img3 from "@/imgs/Interior/جمعية عطاء 62/Untitled-3_result.webp";
import in0_img4 from "@/imgs/Interior/جمعية عطاء 62/Untitled-4_result.webp";
import in0_img5 from "@/imgs/Interior/جمعية عطاء 62/Untitled-5_result.webp";
import in0_img6 from "@/imgs/Interior/جمعية عطاء 62/Untitled-6_result.webp";
import in0_img7 from "@/imgs/Interior/جمعية عطاء 62/Untitled-7_result.webp";
import in0_img8 from "@/imgs/Interior/جمعية عطاء 62/Untitled-8_result.webp";
import in0_img9 from "@/imgs/Interior/جمعية عطاء 62/Untitled-9_result.webp";
import in0_img10 from "@/imgs/Interior/جمعية عطاء 62/Untitled-10_result.webp";
import in0_img11 from "@/imgs/Interior/جمعية عطاء 62/Untitled-11_result.webp";
import in0_img12 from "@/imgs/Interior/جمعية عطاء 62/Untitled-12_result.webp";
import in0_img13 from "@/imgs/Interior/جمعية عطاء 62/Untitled-14_result.webp";
import in0_img14 from "@/imgs/Interior/جمعية عطاء 62/Untitled-15_result.webp";
import in0_img15 from "@/imgs/Interior/جمعية عطاء 62/Untitled-16_result.webp";
import in0_img16 from "@/imgs/Interior/جمعية عطاء 62/Untitled-17_result.webp";
import in0_img17 from "@/imgs/Interior/جمعية عطاء 62/Untitled-18_result.webp";
import in0_img18 from "@/imgs/Interior/جمعية عطاء 62/Untitled-19_result.webp";
import in0_img19 from "@/imgs/Interior/جمعية عطاء 62/Untitled-20_result.webp";
import in0_img20 from "@/imgs/Interior/جمعية عطاء 62/Untitled-21_result.webp";
import in0_img21 from "@/imgs/Interior/جمعية عطاء 62/Untitled-22_result.webp";

export const images: StaticImageData[] = [in0_img0, in0_img1, in0_img2, in0_img3, in0_img4, in0_img5, in0_img6, in0_img7, in0_img8, in0_img9, in0_img10, in0_img11, in0_img12, in0_img13, in0_img14, in0_img15, in0_img16, in0_img17, in0_img18, in0_img19, in0_img20, in0_img21];
