/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in1_img0 from "@/imgs/Interior/ala absi 2/ODAY_result.webp";
import in1_img1 from "@/imgs/Interior/ala absi 2/Untitled-1_result.webp";
import in1_img2 from "@/imgs/Interior/ala absi 2/Untitled-2_result.webp";
import in1_img3 from "@/imgs/Interior/ala absi 2/Untitled-4_result.webp";
import in1_img4 from "@/imgs/Interior/ala absi 2/Untitled-6_result.webp";
import in1_img5 from "@/imgs/Interior/ala absi 2/Untitled-7_result.webp";
import in1_img6 from "@/imgs/Interior/ala absi 2/Untitled-8_result.webp";
import in1_img7 from "@/imgs/Interior/ala absi 2/Untitled-9_result.webp";
import in1_img8 from "@/imgs/Interior/ala absi 2/Untitled-10_result.webp";
import in1_img9 from "@/imgs/Interior/ala absi 2/Untitled-12_result.webp";
import in1_img10 from "@/imgs/Interior/ala absi 2/Untitled-14_result.webp";
import in1_img11 from "@/imgs/Interior/ala absi 2/Untitled-16_result.webp";
import in1_img12 from "@/imgs/Interior/ala absi 2/Untitled-17_result.webp";

export const images: StaticImageData[] = [in1_img0, in1_img1, in1_img2, in1_img3, in1_img4, in1_img5, in1_img6, in1_img7, in1_img8, in1_img9, in1_img10, in1_img11, in1_img12];
