/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in2_img0 from "@/imgs/Interior/baha ahmad 7/ODAY_result.webp";
import in2_img1 from "@/imgs/Interior/baha ahmad 7/Untitled-2 copy_result.webp";
import in2_img2 from "@/imgs/Interior/baha ahmad 7/Untitled-3 copy_result.webp";
import in2_img3 from "@/imgs/Interior/baha ahmad 7/Untitled-4 copy_result.webp";
import in2_img4 from "@/imgs/Interior/baha ahmad 7/Untitled-5 copy_result.webp";
import in2_img5 from "@/imgs/Interior/baha ahmad 7/Untitled-6 copy_result.webp";
import in2_img6 from "@/imgs/Interior/baha ahmad 7/Untitled-7 copy_result.webp";
import in2_img7 from "@/imgs/Interior/baha ahmad 7/Untitled-8 copy_result.webp";
import in2_img8 from "@/imgs/Interior/baha ahmad 7/Untitled-9 copy_result.webp";
import in2_img9 from "@/imgs/Interior/baha ahmad 7/Untitled-10 copy_result.webp";
import in2_img10 from "@/imgs/Interior/baha ahmad 7/Untitled-11 copy_result.webp";
import in2_img11 from "@/imgs/Interior/baha ahmad 7/Untitled-13 copy_result.webp";
import in2_img12 from "@/imgs/Interior/baha ahmad 7/Untitled-14 copy_result.webp";

export const images: StaticImageData[] = [in2_img0, in2_img1, in2_img2, in2_img3, in2_img4, in2_img5, in2_img6, in2_img7, in2_img8, in2_img9, in2_img10, in2_img11, in2_img12];
