/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in3_img0 from "@/imgs/Interior/barber shop 9/ODAY_result.webp";
import in3_img1 from "@/imgs/Interior/barber shop 9/1_result.webp";
import in3_img2 from "@/imgs/Interior/barber shop 9/2_result.webp";
import in3_img3 from "@/imgs/Interior/barber shop 9/3 _result.webp";
import in3_img4 from "@/imgs/Interior/barber shop 9/5 _result.webp";
import in3_img5 from "@/imgs/Interior/barber shop 9/6_result.webp";
import in3_img6 from "@/imgs/Interior/barber shop 9/8_result.webp";
import in3_img7 from "@/imgs/Interior/barber shop 9/9_result.webp";

export const images: StaticImageData[] = [in3_img0, in3_img1, in3_img2, in3_img3, in3_img4, in3_img5, in3_img6, in3_img7];
