/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in4_img0 from "@/imgs/Interior/batool 10/ODAY_result.webp";
import in4_img1 from "@/imgs/Interior/batool 10/2 copy_result.webp";
import in4_img2 from "@/imgs/Interior/batool 10/4 copy_result.webp";
import in4_img3 from "@/imgs/Interior/batool 10/5 copy_result.webp";
import in4_img4 from "@/imgs/Interior/batool 10/6 copy_result.webp";
import in4_img5 from "@/imgs/Interior/batool 10/10 copy_result.webp";
import in4_img6 from "@/imgs/Interior/batool 10/13 copy_result.webp";
import in4_img7 from "@/imgs/Interior/batool 10/15 copy_result.webp";
import in4_img8 from "@/imgs/Interior/batool 10/16 copy_result.webp";
import in4_img9 from "@/imgs/Interior/batool 10/18 copy_result.webp";
import in4_img10 from "@/imgs/Interior/batool 10/19 copy_result.webp";
import in4_img11 from "@/imgs/Interior/batool 10/20 copy_result.webp";

export const images: StaticImageData[] = [in4_img0, in4_img1, in4_img2, in4_img3, in4_img4, in4_img5, in4_img6, in4_img7, in4_img8, in4_img9, in4_img10, in4_img11];
