/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in5_img0 from "@/imgs/Interior/COCO nails 11/ODAY_result.webp";
import in5_img1 from "@/imgs/Interior/COCO nails 11/18_result.webp";
import in5_img2 from "@/imgs/Interior/COCO nails 11/20_result.webp";
import in5_img3 from "@/imgs/Interior/COCO nails 11/21_result.webp";
import in5_img4 from "@/imgs/Interior/COCO nails 11/22_result.webp";
import in5_img5 from "@/imgs/Interior/COCO nails 11/23_result.webp";
import in5_img6 from "@/imgs/Interior/COCO nails 11/24_result.webp";
import in5_img7 from "@/imgs/Interior/COCO nails 11/25_result.webp";
import in5_img8 from "@/imgs/Interior/COCO nails 11/26_result.webp";
import in5_img9 from "@/imgs/Interior/COCO nails 11/27_result.webp";
import in5_img10 from "@/imgs/Interior/COCO nails 11/28_result.webp";
import in5_img11 from "@/imgs/Interior/COCO nails 11/final rend copy_result.webp";

export const images: StaticImageData[] = [in5_img0, in5_img1, in5_img2, in5_img3, in5_img4, in5_img5, in5_img6, in5_img7, in5_img8, in5_img9, in5_img10, in5_img11];
