/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in12_img0 from "@/imgs/Interior/dunats 19/ODAY_result.webp";
import in12_img1 from "@/imgs/Interior/dunats 19/Untitled-1_result.webp";
import in12_img2 from "@/imgs/Interior/dunats 19/Untitled-2_result.webp";
import in12_img3 from "@/imgs/Interior/dunats 19/Untitled-4_result.webp";
import in12_img4 from "@/imgs/Interior/dunats 19/Untitled-5_result.webp";
import in12_img5 from "@/imgs/Interior/dunats 19/Untitled-6_result.webp";
import in12_img6 from "@/imgs/Interior/dunats 19/Untitled-7_result.webp";
import in12_img7 from "@/imgs/Interior/dunats 19/Untitled-8_result.webp";
import in12_img8 from "@/imgs/Interior/dunats 19/Untitled-9_result.webp";
import in12_img9 from "@/imgs/Interior/dunats 19/Untitled-10_result.webp";
import in12_img10 from "@/imgs/Interior/dunats 19/Untitled-11_result.webp";
import in12_img11 from "@/imgs/Interior/dunats 19/Untitled-12_result.webp";

export const images: StaticImageData[] = [in12_img0, in12_img1, in12_img2, in12_img3, in12_img4, in12_img5, in12_img6, in12_img7, in12_img8, in12_img9, in12_img10, in12_img11];
