/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in11_img0 from "@/imgs/Interior/dr salah 17/ODAY_result.webp";
import in11_img1 from "@/imgs/Interior/dr salah 17/1 copy_result.webp";
import in11_img2 from "@/imgs/Interior/dr salah 17/2 copy_result.webp";
import in11_img3 from "@/imgs/Interior/dr salah 17/3 copy_result.webp";
import in11_img4 from "@/imgs/Interior/dr salah 17/4 copy_result.webp";
import in11_img5 from "@/imgs/Interior/dr salah 17/5 copy_result.webp";
import in11_img6 from "@/imgs/Interior/dr salah 17/6 copy_result.webp";
import in11_img7 from "@/imgs/Interior/dr salah 17/7 copy_result.webp";
import in11_img8 from "@/imgs/Interior/dr salah 17/8 copy_result.webp";
import in11_img9 from "@/imgs/Interior/dr salah 17/9 copy_result.webp";
import in11_img10 from "@/imgs/Interior/dr salah 17/10 copy_result.webp";
import in11_img11 from "@/imgs/Interior/dr salah 17/11 copy_result.webp";
import in11_img12 from "@/imgs/Interior/dr salah 17/13 copy_result.webp";
import in11_img13 from "@/imgs/Interior/dr salah 17/14 copy_result.webp";
import in11_img14 from "@/imgs/Interior/dr salah 17/15 copy_result.webp";
import in11_img15 from "@/imgs/Interior/dr salah 17/16 copy_result.webp";
import in11_img16 from "@/imgs/Interior/dr salah 17/17 copy_result.webp";
import in11_img17 from "@/imgs/Interior/dr salah 17/18 copy_result.webp";
import in11_img18 from "@/imgs/Interior/dr salah 17/20 copy_result.webp";
import in11_img19 from "@/imgs/Interior/dr salah 17/22 copy_result.webp";
import in11_img20 from "@/imgs/Interior/dr salah 17/25 copy_result.webp";

export const images: StaticImageData[] = [in11_img0, in11_img1, in11_img2, in11_img3, in11_img4, in11_img5, in11_img6, in11_img7, in11_img8, in11_img9, in11_img10, in11_img11, in11_img12, in11_img13, in11_img14, in11_img15, in11_img16, in11_img17, in11_img18, in11_img19, in11_img20];
