/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in6_img0 from "@/imgs/Interior/diaaab 11/ODAY_result.webp";
import in6_img1 from "@/imgs/Interior/diaaab 11/1 copy_result.webp";
import in6_img2 from "@/imgs/Interior/diaaab 11/3 copy_result.webp";
import in6_img3 from "@/imgs/Interior/diaaab 11/4 copy_result.webp";
import in6_img4 from "@/imgs/Interior/diaaab 11/6 copy_result.webp";
import in6_img5 from "@/imgs/Interior/diaaab 11/7 copy_result.webp";
import in6_img6 from "@/imgs/Interior/diaaab 11/8 copy_result.webp";
import in6_img7 from "@/imgs/Interior/diaaab 11/9 copy_result.webp";
import in6_img8 from "@/imgs/Interior/diaaab 11/10 copy_result.webp";
import in6_img9 from "@/imgs/Interior/diaaab 11/12 copy_result.webp";
import in6_img10 from "@/imgs/Interior/diaaab 11/13 copy_result.webp";

export const images: StaticImageData[] = [in6_img0, in6_img1, in6_img2, in6_img3, in6_img4, in6_img5, in6_img6, in6_img7, in6_img8, in6_img9, in6_img10];
