/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in10_img0 from "@/imgs/Interior/dr raya 16/ODAY_result.webp";
import in10_img1 from "@/imgs/Interior/dr raya 16/Corona Camera001 copy_result.webp";
import in10_img2 from "@/imgs/Interior/dr raya 16/Corona Camera002 copy_result.webp";
import in10_img3 from "@/imgs/Interior/dr raya 16/Corona Camera003 copy_result.webp";
import in10_img4 from "@/imgs/Interior/dr raya 16/Corona Camera006 copy_result.webp";
import in10_img5 from "@/imgs/Interior/dr raya 16/Corona Camera007 copy_result.webp";
import in10_img6 from "@/imgs/Interior/dr raya 16/Corona Camera008 copy_result.webp";
import in10_img7 from "@/imgs/Interior/dr raya 16/Corona Camera009 copy_result.webp";
import in10_img8 from "@/imgs/Interior/dr raya 16/Corona Camera010 copy_result.webp";
import in10_img9 from "@/imgs/Interior/dr raya 16/Corona Camera011 copy_result.webp";
import in10_img10 from "@/imgs/Interior/dr raya 16/Corona Camera012 copy_result.webp";
import in10_img11 from "@/imgs/Interior/dr raya 16/Corona Camera013 copy_result.webp";
import in10_img12 from "@/imgs/Interior/dr raya 16/Corona Camera014 copy_result.webp";
import in10_img13 from "@/imgs/Interior/dr raya 16/Corona Camera015 copy_result.webp";
import in10_img14 from "@/imgs/Interior/dr raya 16/Corona Camera016 copy_result.webp";
import in10_img15 from "@/imgs/Interior/dr raya 16/Corona Camera017 copy_result.webp";
import in10_img16 from "@/imgs/Interior/dr raya 16/Corona Camera018 copy_result.webp";
import in10_img17 from "@/imgs/Interior/dr raya 16/Corona Camera019 copy_result.webp";

export const images: StaticImageData[] = [in10_img0, in10_img1, in10_img2, in10_img3, in10_img4, in10_img5, in10_img6, in10_img7, in10_img8, in10_img9, in10_img10, in10_img11, in10_img12, in10_img13, in10_img14, in10_img15, in10_img16, in10_img17];
