/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in9_img0 from "@/imgs/Interior/dr raed medical center 15/ODAY_result.webp";
import in9_img1 from "@/imgs/Interior/dr raed medical center 15/C2_result.webp";
import in9_img2 from "@/imgs/Interior/dr raed medical center 15/C3_result.webp";
import in9_img3 from "@/imgs/Interior/dr raed medical center 15/C4_result.webp";
import in9_img4 from "@/imgs/Interior/dr raed medical center 15/C5_result.webp";
import in9_img5 from "@/imgs/Interior/dr raed medical center 15/C6_result.webp";
import in9_img6 from "@/imgs/Interior/dr raed medical center 15/C7_result.webp";
import in9_img7 from "@/imgs/Interior/dr raed medical center 15/C8_result.webp";
import in9_img8 from "@/imgs/Interior/dr raed medical center 15/C9_result.webp";
import in9_img9 from "@/imgs/Interior/dr raed medical center 15/C11_result.webp";
import in9_img10 from "@/imgs/Interior/dr raed medical center 15/C12_result.webp";
import in9_img11 from "@/imgs/Interior/dr raed medical center 15/C13_result.webp";
import in9_img12 from "@/imgs/Interior/dr raed medical center 15/C14_result.webp";

export const images: StaticImageData[] = [in9_img0, in9_img1, in9_img2, in9_img3, in9_img4, in9_img5, in9_img6, in9_img7, in9_img8, in9_img9, in9_img10, in9_img11, in9_img12];
