/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in7_img0 from "@/imgs/Interior/DR ABED EL9ADER 12/ODAY_result.webp";
import in7_img1 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-1_result.webp";
import in7_img2 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-2_result.webp";
import in7_img3 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-3_result.webp";
import in7_img4 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-4_result.webp";
import in7_img5 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-5_result.webp";
import in7_img6 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-6_result.webp";
import in7_img7 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-7_result.webp";
import in7_img8 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-9_result.webp";
import in7_img9 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-10_result.webp";
import in7_img10 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-11_result.webp";
import in7_img11 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-12_result.webp";
import in7_img12 from "@/imgs/Interior/DR ABED EL9ADER 12/Untitled-13_result.webp";

export const images: StaticImageData[] = [in7_img0, in7_img1, in7_img2, in7_img3, in7_img4, in7_img5, in7_img6, in7_img7, in7_img8, in7_img9, in7_img10, in7_img11, in7_img12];
