/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in8_img0 from "@/imgs/Interior/dr amal duaibes 13/ODAY_result.webp";
import in8_img1 from "@/imgs/Interior/dr amal duaibes 13/OF 1.1 copy_result.webp";
import in8_img2 from "@/imgs/Interior/dr amal duaibes 13/OF 1.2 copy_result.webp";
import in8_img3 from "@/imgs/Interior/dr amal duaibes 13/OF 1.003 copy_result.webp";
import in8_img4 from "@/imgs/Interior/dr amal duaibes 13/OF 1.004 copy_result.webp";
import in8_img5 from "@/imgs/Interior/dr amal duaibes 13/OF 1.005 copy_result.webp";
import in8_img6 from "@/imgs/Interior/dr amal duaibes 13/OF 1.008 copy_result.webp";
import in8_img7 from "@/imgs/Interior/dr amal duaibes 13/OF 1.012 copy_result.webp";
import in8_img8 from "@/imgs/Interior/dr amal duaibes 13/OF 1.013 copy_result.webp";
import in8_img9 from "@/imgs/Interior/dr amal duaibes 13/OF 1.014 copy_result.webp";
import in8_img10 from "@/imgs/Interior/dr amal duaibes 13/OF 1.015 copy_result.webp";
import in8_img11 from "@/imgs/Interior/dr amal duaibes 13/OF 2.1 copy_result.webp";
import in8_img12 from "@/imgs/Interior/dr amal duaibes 13/OF 2.2 copy_result.webp";
import in8_img13 from "@/imgs/Interior/dr amal duaibes 13/OF 2.003 copy_result.webp";
import in8_img14 from "@/imgs/Interior/dr amal duaibes 13/OF 2.004 copy_result.webp";
import in8_img15 from "@/imgs/Interior/dr amal duaibes 13/OF 3.1 copy_result.webp";
import in8_img16 from "@/imgs/Interior/dr amal duaibes 13/OF 3.2 copy_result.webp";
import in8_img17 from "@/imgs/Interior/dr amal duaibes 13/R 02 copy_result.webp";
import in8_img18 from "@/imgs/Interior/dr amal duaibes 13/R 03 copy_result.webp";
import in8_img19 from "@/imgs/Interior/dr amal duaibes 13/R 04 copy_result.webp";
import in8_img20 from "@/imgs/Interior/dr amal duaibes 13/R 05 copy_result.webp";

export const images: StaticImageData[] = [in8_img0, in8_img1, in8_img2, in8_img3, in8_img4, in8_img5, in8_img6, in8_img7, in8_img8, in8_img9, in8_img10, in8_img11, in8_img12, in8_img13, in8_img14, in8_img15, in8_img16, in8_img17, in8_img18, in8_img19, in8_img20];
