/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in13_img0 from "@/imgs/Interior/FARED MALABES 20/ODAY_result.webp";
import in13_img1 from "@/imgs/Interior/FARED MALABES 20/2bb60687-36bf-452a-9d03-ae80c4f01946_result.webp";
import in13_img2 from "@/imgs/Interior/FARED MALABES 20/2fa0e993-6f91-49aa-8d2a-ccf10249bdf0_result.webp";
import in13_img3 from "@/imgs/Interior/FARED MALABES 20/03ecb243-c445-409d-991b-3710278efd3f_result.webp";
import in13_img4 from "@/imgs/Interior/FARED MALABES 20/8e2bd822-ad2f-4292-82d4-809c231c758b_result.webp";
import in13_img5 from "@/imgs/Interior/FARED MALABES 20/9aee33ce-c640-4777-96ff-dba5249b42f8_result.webp";
import in13_img6 from "@/imgs/Interior/FARED MALABES 20/023a56fc-3209-4ee3-b862-c641f976a38c_result.webp";
import in13_img7 from "@/imgs/Interior/FARED MALABES 20/51f58fad-2ae6-4973-8df1-13cdbd99423e_result.webp";
import in13_img8 from "@/imgs/Interior/FARED MALABES 20/be960a3b-0071-44d2-bbcb-855cf86d9a63_result.webp";

export const images: StaticImageData[] = [in13_img0, in13_img1, in13_img2, in13_img3, in13_img4, in13_img5, in13_img6, in13_img7, in13_img8];
