/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in14_img0 from "@/imgs/Interior/fareed bridal shop 21/ODAY_result.webp";
import in14_img1 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.17 PM (1) copy_result.webp";
import in14_img2 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.17 PM (2) copy_result.webp";
import in14_img3 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.18 PM (1) copy_result.webp";
import in14_img4 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.18 PM (3) copy_result.webp";
import in14_img5 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.18 PM (4) copy_result.webp";
import in14_img6 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.18 PM (5) copy_result.webp";
import in14_img7 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.18 PM (6) copy_result.webp";
import in14_img8 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.18 PM (7) copy_result.webp";
import in14_img9 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.18 PM (8) copy_result.webp";
import in14_img10 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.18 PM (9) copy_result.webp";
import in14_img11 from "@/imgs/Interior/fareed bridal shop 21/WhatsApp Image 2024-06-17 at 7.13.18 PM copy_result.webp";

export const images: StaticImageData[] = [in14_img0, in14_img1, in14_img2, in14_img3, in14_img4, in14_img5, in14_img6, in14_img7, in14_img8, in14_img9, in14_img10, in14_img11];
