/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in16_img0 from "@/imgs/Interior/ghaleb 23/ODAY_result.webp";
import in16_img1 from "@/imgs/Interior/ghaleb 23/3 copy_result.webp";
import in16_img2 from "@/imgs/Interior/ghaleb 23/4 copy_result.webp";
import in16_img3 from "@/imgs/Interior/ghaleb 23/5 copy_result.webp";
import in16_img4 from "@/imgs/Interior/ghaleb 23/6 copy_result.webp";
import in16_img5 from "@/imgs/Interior/ghaleb 23/7 copy_result.webp";
import in16_img6 from "@/imgs/Interior/ghaleb 23/8 copy_result.webp";
import in16_img7 from "@/imgs/Interior/ghaleb 23/13 copy_result.webp";
import in16_img8 from "@/imgs/Interior/ghaleb 23/14 copy_result.webp";
import in16_img9 from "@/imgs/Interior/ghaleb 23/15 copy_result.webp";
import in16_img10 from "@/imgs/Interior/ghaleb 23/18 copy_result.webp";
import in16_img11 from "@/imgs/Interior/ghaleb 23/19 copy_result.webp";
import in16_img12 from "@/imgs/Interior/ghaleb 23/20 copy_result.webp";
import in16_img13 from "@/imgs/Interior/ghaleb 23/23 copy_result.webp";
import in16_img14 from "@/imgs/Interior/ghaleb 23/24 copy_result.webp";
import in16_img15 from "@/imgs/Interior/ghaleb 23/27 copy_result.webp";

export const images: StaticImageData[] = [in16_img0, in16_img1, in16_img2, in16_img3, in16_img4, in16_img5, in16_img6, in16_img7, in16_img8, in16_img9, in16_img10, in16_img11, in16_img12, in16_img13, in16_img14, in16_img15];
