/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in15_img0 from "@/imgs/Interior/ghaleb 22/ODAY_result.webp";
import in15_img1 from "@/imgs/Interior/ghaleb 22/Corona Camera001 copy_result.webp";
import in15_img2 from "@/imgs/Interior/ghaleb 22/Corona Camera003 copy_result.webp";
import in15_img3 from "@/imgs/Interior/ghaleb 22/Corona Camera004 copy_result.webp";
import in15_img4 from "@/imgs/Interior/ghaleb 22/Corona Camera006 copy_result.webp";
import in15_img5 from "@/imgs/Interior/ghaleb 22/Corona Camera007 copy_result.webp";
import in15_img6 from "@/imgs/Interior/ghaleb 22/Corona Camera008 copy_result.webp";
import in15_img7 from "@/imgs/Interior/ghaleb 22/Corona Camera009 copy_result.webp";
import in15_img8 from "@/imgs/Interior/ghaleb 22/Corona Camera010 copy_result.webp";
import in15_img9 from "@/imgs/Interior/ghaleb 22/Corona Camera011 copy_result.webp";
import in15_img10 from "@/imgs/Interior/ghaleb 22/Corona Camera012 copy_result.webp";
import in15_img11 from "@/imgs/Interior/ghaleb 22/Corona Camera013 copy_result.webp";

export const images: StaticImageData[] = [in15_img0, in15_img1, in15_img2, in15_img3, in15_img4, in15_img5, in15_img6, in15_img7, in15_img8, in15_img9, in15_img10, in15_img11];
