/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in20_img0 from "@/imgs/Interior/Howida 3th floor option 32/ODAY_result.webp";
import in20_img1 from "@/imgs/Interior/Howida 3th floor option 32/34 copy_result.webp";
import in20_img2 from "@/imgs/Interior/Howida 3th floor option 32/35 copy_result.webp";
import in20_img3 from "@/imgs/Interior/Howida 3th floor option 32/36  copy_result.webp";
import in20_img4 from "@/imgs/Interior/Howida 3th floor option 32/37 copy_result.webp";
import in20_img5 from "@/imgs/Interior/Howida 3th floor option 32/38 copy_result.webp";
import in20_img6 from "@/imgs/Interior/Howida 3th floor option 32/39 copy_result.webp";
import in20_img7 from "@/imgs/Interior/Howida 3th floor option 32/40  copy_result.webp";
import in20_img8 from "@/imgs/Interior/Howida 3th floor option 32/41 copy_result.webp";
import in20_img9 from "@/imgs/Interior/Howida 3th floor option 32/42 copy_result.webp";
import in20_img10 from "@/imgs/Interior/Howida 3th floor option 32/43 copy_result.webp";
import in20_img11 from "@/imgs/Interior/Howida 3th floor option 32/44 copy_result.webp";
import in20_img12 from "@/imgs/Interior/Howida 3th floor option 32/45 copy_result.webp";
import in20_img13 from "@/imgs/Interior/Howida 3th floor option 32/47 copy_result.webp";

export const images: StaticImageData[] = [in20_img0, in20_img1, in20_img2, in20_img3, in20_img4, in20_img5, in20_img6, in20_img7, in20_img8, in20_img9, in20_img10, in20_img11, in20_img12, in20_img13];
