/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in17_img0 from "@/imgs/Interior/Howida  cottage 28/ODAY_result.webp";
import in17_img1 from "@/imgs/Interior/Howida  cottage 28/2 copy_result.webp";
import in17_img2 from "@/imgs/Interior/Howida  cottage 28/4 copy_result.webp";
import in17_img3 from "@/imgs/Interior/Howida  cottage 28/5 copy_result.webp";
import in17_img4 from "@/imgs/Interior/Howida  cottage 28/6 copy_result.webp";
import in17_img5 from "@/imgs/Interior/Howida  cottage 28/7 copy_result.webp";
import in17_img6 from "@/imgs/Interior/Howida  cottage 28/8 copy_result.webp";
import in17_img7 from "@/imgs/Interior/Howida  cottage 28/9 copy_result.webp";
import in17_img8 from "@/imgs/Interior/Howida  cottage 28/10 copy_result.webp";
import in17_img9 from "@/imgs/Interior/Howida  cottage 28/11 copy_result.webp";
import in17_img10 from "@/imgs/Interior/Howida  cottage 28/12 copy_result.webp";
import in17_img11 from "@/imgs/Interior/Howida  cottage 28/13 copy_result.webp";
import in17_img12 from "@/imgs/Interior/Howida  cottage 28/14 copy_result.webp";
import in17_img13 from "@/imgs/Interior/Howida  cottage 28/15 copy_result.webp";
import in17_img14 from "@/imgs/Interior/Howida  cottage 28/16 copy_result.webp";
import in17_img15 from "@/imgs/Interior/Howida  cottage 28/17 copy_result.webp";

export const images: StaticImageData[] = [in17_img0, in17_img1, in17_img2, in17_img3, in17_img4, in17_img5, in17_img6, in17_img7, in17_img8, in17_img9, in17_img10, in17_img11, in17_img12, in17_img13, in17_img14, in17_img15];
