/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in18_img0 from "@/imgs/Interior/Howida  Living Room Render's 29/ODAY_result.webp";
import in18_img1 from "@/imgs/Interior/Howida  Living Room Render's 29/1_result.webp";
import in18_img2 from "@/imgs/Interior/Howida  Living Room Render's 29/2_result.webp";
import in18_img3 from "@/imgs/Interior/Howida  Living Room Render's 29/3_result.webp";
import in18_img4 from "@/imgs/Interior/Howida  Living Room Render's 29/4_result.webp";
import in18_img5 from "@/imgs/Interior/Howida  Living Room Render's 29/5_result.webp";
import in18_img6 from "@/imgs/Interior/Howida  Living Room Render's 29/6_result.webp";
import in18_img7 from "@/imgs/Interior/Howida  Living Room Render's 29/7_result.webp";
import in18_img8 from "@/imgs/Interior/Howida  Living Room Render's 29/8_result.webp";
import in18_img9 from "@/imgs/Interior/Howida  Living Room Render's 29/9_result.webp";
import in18_img10 from "@/imgs/Interior/Howida  Living Room Render's 29/10_result.webp";
import in18_img11 from "@/imgs/Interior/Howida  Living Room Render's 29/11_result.webp";
import in18_img12 from "@/imgs/Interior/Howida  Living Room Render's 29/12_result.webp";
import in18_img13 from "@/imgs/Interior/Howida  Living Room Render's 29/13_result.webp";
import in18_img14 from "@/imgs/Interior/Howida  Living Room Render's 29/14_result.webp";
import in18_img15 from "@/imgs/Interior/Howida  Living Room Render's 29/15 copy_result.webp";
import in18_img16 from "@/imgs/Interior/Howida  Living Room Render's 29/16 copy_result.webp";
import in18_img17 from "@/imgs/Interior/Howida  Living Room Render's 29/17_result.webp";
import in18_img18 from "@/imgs/Interior/Howida  Living Room Render's 29/19_result.webp";
import in18_img19 from "@/imgs/Interior/Howida  Living Room Render's 29/20 copy_result.webp";
import in18_img20 from "@/imgs/Interior/Howida  Living Room Render's 29/21 copy_result.webp";

export const images: StaticImageData[] = [in18_img0, in18_img1, in18_img2, in18_img3, in18_img4, in18_img5, in18_img6, in18_img7, in18_img8, in18_img9, in18_img10, in18_img11, in18_img12, in18_img13, in18_img14, in18_img15, in18_img16, in18_img17, in18_img18, in18_img19, in18_img20];
