/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in19_img0 from "@/imgs/Interior/Howida  Master Bed Room render's 31/ODAY_result.webp";
import in19_img1 from "@/imgs/Interior/Howida  Master Bed Room render's 31/1 copy_result.webp";
import in19_img2 from "@/imgs/Interior/Howida  Master Bed Room render's 31/4 copy_result.webp";
import in19_img3 from "@/imgs/Interior/Howida  Master Bed Room render's 31/9c_result.webp";
import in19_img4 from "@/imgs/Interior/Howida  Master Bed Room render's 31/10c_result.webp";
import in19_img5 from "@/imgs/Interior/Howida  Master Bed Room render's 31/11 copy_result.webp";
import in19_img6 from "@/imgs/Interior/Howida  Master Bed Room render's 31/12c_result.webp";
import in19_img7 from "@/imgs/Interior/Howida  Master Bed Room render's 31/13 copy_result.webp";
import in19_img8 from "@/imgs/Interior/Howida  Master Bed Room render's 31/14 copy_result.webp";
import in19_img9 from "@/imgs/Interior/Howida  Master Bed Room render's 31/15_result.webp";
import in19_img10 from "@/imgs/Interior/Howida  Master Bed Room render's 31/16_result.webp";
import in19_img11 from "@/imgs/Interior/Howida  Master Bed Room render's 31/17 copy_result.webp";
import in19_img12 from "@/imgs/Interior/Howida  Master Bed Room render's 31/18 copy_result.webp";
import in19_img13 from "@/imgs/Interior/Howida  Master Bed Room render's 31/19 copy_result.webp";
import in19_img14 from "@/imgs/Interior/Howida  Master Bed Room render's 31/21_result.webp";
import in19_img15 from "@/imgs/Interior/Howida  Master Bed Room render's 31/22 copy_result.webp";
import in19_img16 from "@/imgs/Interior/Howida  Master Bed Room render's 31/23_result.webp";
import in19_img17 from "@/imgs/Interior/Howida  Master Bed Room render's 31/24 copy_result.webp";
import in19_img18 from "@/imgs/Interior/Howida  Master Bed Room render's 31/25 copy_result.webp";
import in19_img19 from "@/imgs/Interior/Howida  Master Bed Room render's 31/26 copy_result.webp";
import in19_img20 from "@/imgs/Interior/Howida  Master Bed Room render's 31/27 copy_result.webp";
import in19_img21 from "@/imgs/Interior/Howida  Master Bed Room render's 31/28 copy_result.webp";
import in19_img22 from "@/imgs/Interior/Howida  Master Bed Room render's 31/31 copy_result.webp";
import in19_img23 from "@/imgs/Interior/Howida  Master Bed Room render's 31/32 copy_result.webp";
import in19_img24 from "@/imgs/Interior/Howida  Master Bed Room render's 31/33_result.webp";
import in19_img25 from "@/imgs/Interior/Howida  Master Bed Room render's 31/34 copy_result.webp";
import in19_img26 from "@/imgs/Interior/Howida  Master Bed Room render's 31/60 copy_result.webp";
import in19_img27 from "@/imgs/Interior/Howida  Master Bed Room render's 31/63 copy_result.webp";

export const images: StaticImageData[] = [in19_img0, in19_img1, in19_img2, in19_img3, in19_img4, in19_img5, in19_img6, in19_img7, in19_img8, in19_img9, in19_img10, in19_img11, in19_img12, in19_img13, in19_img14, in19_img15, in19_img16, in19_img17, in19_img18, in19_img19, in19_img20, in19_img21, in19_img22, in19_img23, in19_img24, in19_img25, in19_img26, in19_img27];
