/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in21_img0 from "@/imgs/Interior/kitchen omar 34/oday_result.webp";
import in21_img1 from "@/imgs/Interior/kitchen omar 34/C1 copy_result.webp";
import in21_img2 from "@/imgs/Interior/kitchen omar 34/C2 copy_result.webp";
import in21_img3 from "@/imgs/Interior/kitchen omar 34/C3 copy_result.webp";
import in21_img4 from "@/imgs/Interior/kitchen omar 34/C4 copy_result.webp";
import in21_img5 from "@/imgs/Interior/kitchen omar 34/C5 copy_result.webp";
import in21_img6 from "@/imgs/Interior/kitchen omar 34/C7 copy_result.webp";
import in21_img7 from "@/imgs/Interior/kitchen omar 34/C8 copy_result.webp";
import in21_img8 from "@/imgs/Interior/kitchen omar 34/C9 copy_result.webp";

export const images: StaticImageData[] = [in21_img0, in21_img1, in21_img2, in21_img3, in21_img4, in21_img5, in21_img6, in21_img7, in21_img8];
