/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in22_img0 from "@/imgs/Interior/market 38/oday_result.webp";
import in22_img1 from "@/imgs/Interior/market 38/1_View01 copy_result.webp";
import in22_img2 from "@/imgs/Interior/market 38/1_View03 copy_result.webp";
import in22_img3 from "@/imgs/Interior/market 38/1_View04 copy_result.webp";
import in22_img4 from "@/imgs/Interior/market 38/1_View05 copy_result.webp";
import in22_img5 from "@/imgs/Interior/market 38/1_View06 copy_result.webp";
import in22_img6 from "@/imgs/Interior/market 38/1_View07 copy_result.webp";
import in22_img7 from "@/imgs/Interior/market 38/1_View08 copy_result.webp";
import in22_img8 from "@/imgs/Interior/market 38/1_View10 copy_result.webp";
import in22_img9 from "@/imgs/Interior/market 38/1_View11 copy_result.webp";
import in22_img10 from "@/imgs/Interior/market 38/1_View13 copy_result.webp";
import in22_img11 from "@/imgs/Interior/market 38/1_View14 copy_result.webp";
import in22_img12 from "@/imgs/Interior/market 38/1_View15 copy_result.webp";
import in22_img13 from "@/imgs/Interior/market 38/1_View16 copy_result.webp";
import in22_img14 from "@/imgs/Interior/market 38/1_View17 copy_result.webp";
import in22_img15 from "@/imgs/Interior/market 38/1_View18 copy_result.webp";
import in22_img16 from "@/imgs/Interior/market 38/1_View19 copy_result.webp";

export const images: StaticImageData[] = [in22_img0, in22_img1, in22_img2, in22_img3, in22_img4, in22_img5, in22_img6, in22_img7, in22_img8, in22_img9, in22_img10, in22_img11, in22_img12, in22_img13, in22_img14, in22_img15, in22_img16];
