/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in23_img0 from "@/imgs/Interior/mohammad nassrallah 39/oday_result.webp";
import in23_img1 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-1_result.webp";
import in23_img2 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-2_result.webp";
import in23_img3 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-3_result.webp";
import in23_img4 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-4_result.webp";
import in23_img5 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-5_result.webp";
import in23_img6 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-7_result.webp";
import in23_img7 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-8_result.webp";
import in23_img8 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-9_result.webp";
import in23_img9 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-10_result.webp";
import in23_img10 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-11_result.webp";
import in23_img11 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-12_result.webp";
import in23_img12 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-13_result.webp";
import in23_img13 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-14_result.webp";
import in23_img14 from "@/imgs/Interior/mohammad nassrallah 39/Untitled-15_result.webp";

export const images: StaticImageData[] = [in23_img0, in23_img1, in23_img2, in23_img3, in23_img4, in23_img5, in23_img6, in23_img7, in23_img8, in23_img9, in23_img10, in23_img11, in23_img12, in23_img13, in23_img14];
