/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in24_img0 from "@/imgs/Interior/motaz falah 41/oday_result.webp";
import in24_img1 from "@/imgs/Interior/motaz falah 41/C1 copy1_result.webp";
import in24_img2 from "@/imgs/Interior/motaz falah 41/C3 copy3_result.webp";
import in24_img3 from "@/imgs/Interior/motaz falah 41/C4 copy4_result.webp";
import in24_img4 from "@/imgs/Interior/motaz falah 41/C5 copy5_result.webp";
import in24_img5 from "@/imgs/Interior/motaz falah 41/C6 copy6_result.webp";
import in24_img6 from "@/imgs/Interior/motaz falah 41/C7 copy7_result.webp";
import in24_img7 from "@/imgs/Interior/motaz falah 41/C8 copy8_result.webp";
import in24_img8 from "@/imgs/Interior/motaz falah 41/C9 copy9_result.webp";
import in24_img9 from "@/imgs/Interior/motaz falah 41/c10 copy10_result.webp";
import in24_img10 from "@/imgs/Interior/motaz falah 41/c11 copy_result.webp";
import in24_img11 from "@/imgs/Interior/motaz falah 41/c12 copy12_result.webp";
import in24_img12 from "@/imgs/Interior/motaz falah 41/c13 copy13_result.webp";
import in24_img13 from "@/imgs/Interior/motaz falah 41/c14 copy14_result.webp";

export const images: StaticImageData[] = [in24_img0, in24_img1, in24_img2, in24_img3, in24_img4, in24_img5, in24_img6, in24_img7, in24_img8, in24_img9, in24_img10, in24_img11, in24_img12, in24_img13];
