/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in27_img0 from "@/imgs/Interior/nizzar showroom 48/oday_result.webp";
import in27_img1 from "@/imgs/Interior/nizzar showroom 48/Corona Camera001 copy_result.webp";
import in27_img2 from "@/imgs/Interior/nizzar showroom 48/Corona Camera002 copy_result.webp";
import in27_img3 from "@/imgs/Interior/nizzar showroom 48/Corona Camera003 copy_result.webp";
import in27_img4 from "@/imgs/Interior/nizzar showroom 48/Corona Camera004 copy_result.webp";
import in27_img5 from "@/imgs/Interior/nizzar showroom 48/Corona Camera005 copy_result.webp";
import in27_img6 from "@/imgs/Interior/nizzar showroom 48/Corona Camera006 copy_result.webp";
import in27_img7 from "@/imgs/Interior/nizzar showroom 48/Corona Camera008 copy_result.webp";
import in27_img8 from "@/imgs/Interior/nizzar showroom 48/Corona Camera009 copy_result.webp";
import in27_img9 from "@/imgs/Interior/nizzar showroom 48/Corona Camera010 copy_result.webp";
import in27_img10 from "@/imgs/Interior/nizzar showroom 48/Corona Camera011 copy_result.webp";
import in27_img11 from "@/imgs/Interior/nizzar showroom 48/Corona Camera012 copy_result.webp";
import in27_img12 from "@/imgs/Interior/nizzar showroom 48/R 04 copy_result.webp";
import in27_img13 from "@/imgs/Interior/nizzar showroom 48/R 06 copy_result.webp";

export const images: StaticImageData[] = [in27_img0, in27_img1, in27_img2, in27_img3, in27_img4, in27_img5, in27_img6, in27_img7, in27_img8, in27_img9, in27_img10, in27_img11, in27_img12, in27_img13];
