/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in26_img0 from "@/imgs/Interior/nizzar laserroom 47/oday_result.webp";
import in26_img1 from "@/imgs/Interior/nizzar laserroom 47/L 01 copy_result.webp";
import in26_img2 from "@/imgs/Interior/nizzar laserroom 47/L 02.1 copy_result.webp";
import in26_img3 from "@/imgs/Interior/nizzar laserroom 47/L 02.2 copy_result.webp";
import in26_img4 from "@/imgs/Interior/nizzar laserroom 47/L 2.3 copy_result.webp";
import in26_img5 from "@/imgs/Interior/nizzar laserroom 47/L 2.004 copy_result.webp";
import in26_img6 from "@/imgs/Interior/nizzar laserroom 47/L 2.005 copy_result.webp";
import in26_img7 from "@/imgs/Interior/nizzar laserroom 47/L 2.006 copy_result.webp";
import in26_img8 from "@/imgs/Interior/nizzar laserroom 47/L 2.007 copy_result.webp";
import in26_img9 from "@/imgs/Interior/nizzar laserroom 47/L 2.008 copy_result.webp";
import in26_img10 from "@/imgs/Interior/nizzar laserroom 47/L 2.009 copy_result.webp";
import in26_img11 from "@/imgs/Interior/nizzar laserroom 47/L 2.010 copy_result.webp";
import in26_img12 from "@/imgs/Interior/nizzar laserroom 47/R 05 copy_result.webp";
import in26_img13 from "@/imgs/Interior/nizzar laserroom 47/R 007 copy_result.webp";
import in26_img14 from "@/imgs/Interior/nizzar laserroom 47/R 008 copy_result.webp";
import in26_img15 from "@/imgs/Interior/nizzar laserroom 47/R 0100 copy_result.webp";

export const images: StaticImageData[] = [in26_img0, in26_img1, in26_img2, in26_img3, in26_img4, in26_img5, in26_img6, in26_img7, in26_img8, in26_img9, in26_img10, in26_img11, in26_img12, in26_img13, in26_img14, in26_img15];
