/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in25_img0 from "@/imgs/Interior/NEVADA BATH 45/oday_result.webp";
import in25_img1 from "@/imgs/Interior/NEVADA BATH 45/c (1)_result.webp";
import in25_img2 from "@/imgs/Interior/NEVADA BATH 45/c (3)_result.webp";
import in25_img3 from "@/imgs/Interior/NEVADA BATH 45/c (4)_result.webp";
import in25_img4 from "@/imgs/Interior/NEVADA BATH 45/C11_result.webp";
import in25_img5 from "@/imgs/Interior/NEVADA BATH 45/C12_result.webp";
import in25_img6 from "@/imgs/Interior/NEVADA BATH 45/C22_result.webp";
import in25_img7 from "@/imgs/Interior/NEVADA BATH 45/C33_result.webp";
import in25_img8 from "@/imgs/Interior/NEVADA BATH 45/C44_result.webp";
import in25_img9 from "@/imgs/Interior/NEVADA BATH 45/C55_result.webp";
import in25_img10 from "@/imgs/Interior/NEVADA BATH 45/C66_result.webp";
import in25_img11 from "@/imgs/Interior/NEVADA BATH 45/C77_result.webp";
import in25_img12 from "@/imgs/Interior/NEVADA BATH 45/C88_result.webp";

export const images: StaticImageData[] = [in25_img0, in25_img1, in25_img2, in25_img3, in25_img4, in25_img5, in25_img6, in25_img7, in25_img8, in25_img9, in25_img10, in25_img11, in25_img12];
