/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in29_img0 from "@/imgs/Interior/rami render 50/oday_result.webp";
import in29_img1 from "@/imgs/Interior/rami render 50/Untitled-1_result.webp";
import in29_img2 from "@/imgs/Interior/rami render 50/Untitled-2_result.webp";
import in29_img3 from "@/imgs/Interior/rami render 50/Untitled-3_result.webp";
import in29_img4 from "@/imgs/Interior/rami render 50/Untitled-5_result.webp";
import in29_img5 from "@/imgs/Interior/rami render 50/Untitled-6_result.webp";
import in29_img6 from "@/imgs/Interior/rami render 50/Untitled-7_result.webp";
import in29_img7 from "@/imgs/Interior/rami render 50/Untitled-8_result.webp";
import in29_img8 from "@/imgs/Interior/rami render 50/Untitled-11_result.webp";
import in29_img9 from "@/imgs/Interior/rami render 50/Untitled-12_result.webp";
import in29_img10 from "@/imgs/Interior/rami render 50/Untitled-13_result.webp";
import in29_img11 from "@/imgs/Interior/rami render 50/Untitled-14_result.webp";
import in29_img12 from "@/imgs/Interior/rami render 50/Untitled-15_result.webp";
import in29_img13 from "@/imgs/Interior/rami render 50/Untitled-16_result.webp";
import in29_img14 from "@/imgs/Interior/rami render 50/Untitled-17_result.webp";

export const images: StaticImageData[] = [in29_img0, in29_img1, in29_img2, in29_img3, in29_img4, in29_img5, in29_img6, in29_img7, in29_img8, in29_img9, in29_img10, in29_img11, in29_img12, in29_img13, in29_img14];
