/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in28_img0 from "@/imgs/Interior/rabee decor 49/oday_result.webp";
import in28_img1 from "@/imgs/Interior/rabee decor 49/2copy_result.webp";
import in28_img2 from "@/imgs/Interior/rabee decor 49/7 copy_result.webp";
import in28_img3 from "@/imgs/Interior/rabee decor 49/8 copy_result.webp";
import in28_img4 from "@/imgs/Interior/rabee decor 49/11copy_result.webp";
import in28_img5 from "@/imgs/Interior/rabee decor 49/12 copy_result.webp";
import in28_img6 from "@/imgs/Interior/rabee decor 49/Corona Camera003GRAY _result.webp";
import in28_img7 from "@/imgs/Interior/rabee decor 49/Corona Camera004 copy_result.webp";
import in28_img8 from "@/imgs/Interior/rabee decor 49/Corona Camera005 copy_result.webp";
import in28_img9 from "@/imgs/Interior/rabee decor 49/Corona Camera009 GRAY_result.webp";
import in28_img10 from "@/imgs/Interior/rabee decor 49/Corona Camera010 copy_result.webp";
import in28_img11 from "@/imgs/Interior/rabee decor 49/Corona Camera013 copy_result.webp";
import in28_img12 from "@/imgs/Interior/rabee decor 49/Corona Camera014 copy_result.webp";
import in28_img13 from "@/imgs/Interior/rabee decor 49/Corona Camera015 copy_result.webp";
import in28_img14 from "@/imgs/Interior/rabee decor 49/Corona Camera016 copy_result.webp";

export const images: StaticImageData[] = [in28_img0, in28_img1, in28_img2, in28_img3, in28_img4, in28_img5, in28_img6, in28_img7, in28_img8, in28_img9, in28_img10, in28_img11, in28_img12, in28_img13, in28_img14];
