/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in31_img0 from "@/imgs/Interior/saleh pizza 53/oday_result.webp";
import in31_img1 from "@/imgs/Interior/saleh pizza 53/Corona Camera001 copy_result.webp";
import in31_img2 from "@/imgs/Interior/saleh pizza 53/Corona Camera002 copy_result.webp";
import in31_img3 from "@/imgs/Interior/saleh pizza 53/Corona Camera003 copy_result.webp";
import in31_img4 from "@/imgs/Interior/saleh pizza 53/Corona Camera004 copy_result.webp";
import in31_img5 from "@/imgs/Interior/saleh pizza 53/Corona Camera005 copy_result.webp";
import in31_img6 from "@/imgs/Interior/saleh pizza 53/Corona Camera008 copy_result.webp";
import in31_img7 from "@/imgs/Interior/saleh pizza 53/Corona Camera009 copy_result.webp";
import in31_img8 from "@/imgs/Interior/saleh pizza 53/Corona Camera010 copy 2_result.webp";
import in31_img9 from "@/imgs/Interior/saleh pizza 53/Corona Camera011 copy_result.webp";
import in31_img10 from "@/imgs/Interior/saleh pizza 53/Corona Camera012 copy_result.webp";
import in31_img11 from "@/imgs/Interior/saleh pizza 53/Corona Camera013 copy_result.webp";
import in31_img12 from "@/imgs/Interior/saleh pizza 53/Corona Camera014 copy_result.webp";
import in31_img13 from "@/imgs/Interior/saleh pizza 53/Corona Camera015 copy_result.webp";
import in31_img14 from "@/imgs/Interior/saleh pizza 53/Corona Camera016 copy_result.webp";
import in31_img15 from "@/imgs/Interior/saleh pizza 53/Corona Camera017 copy_result.webp";
import in31_img16 from "@/imgs/Interior/saleh pizza 53/Corona Camera019 copy_result.webp";
import in31_img17 from "@/imgs/Interior/saleh pizza 53/View07 copy_result.webp";

export const images: StaticImageData[] = [in31_img0, in31_img1, in31_img2, in31_img3, in31_img4, in31_img5, in31_img6, in31_img7, in31_img8, in31_img9, in31_img10, in31_img11, in31_img12, in31_img13, in31_img14, in31_img15, in31_img16, in31_img17];
