/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in30_img0 from "@/imgs/Interior/saleh bedroom 52/oday_result.webp";
import in30_img1 from "@/imgs/Interior/saleh bedroom 52/1_Interactive LightMix_View01 copy_result.webp";
import in30_img2 from "@/imgs/Interior/saleh bedroom 52/1_Interactive LightMix_View02 copy_result.webp";
import in30_img3 from "@/imgs/Interior/saleh bedroom 52/1_Interactive LightMix_View04 copy_result.webp";
import in30_img4 from "@/imgs/Interior/saleh bedroom 52/1_Interactive LightMix_View05 copy_result.webp";
import in30_img5 from "@/imgs/Interior/saleh bedroom 52/1_Interactive LightMix_View06 copy_result.webp";
import in30_img6 from "@/imgs/Interior/saleh bedroom 52/2 copy_result.webp";
import in30_img7 from "@/imgs/Interior/saleh bedroom 52/3 copy_result.webp";
import in30_img8 from "@/imgs/Interior/saleh bedroom 52/4 copy_result.webp";
import in30_img9 from "@/imgs/Interior/saleh bedroom 52/5 copy_result.webp";

export const images: StaticImageData[] = [in30_img0, in30_img1, in30_img2, in30_img3, in30_img4, in30_img5, in30_img6, in30_img7, in30_img8, in30_img9];
