/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in32_img0 from "@/imgs/Interior/saqer 54/oday_result.webp";
import in32_img1 from "@/imgs/Interior/saqer 54/Untitled-1_result.webp";
import in32_img2 from "@/imgs/Interior/saqer 54/Untitled-2_result.webp";
import in32_img3 from "@/imgs/Interior/saqer 54/Untitled-3_result.webp";
import in32_img4 from "@/imgs/Interior/saqer 54/Untitled-5_result.webp";
import in32_img5 from "@/imgs/Interior/saqer 54/Untitled-6_result.webp";
import in32_img6 from "@/imgs/Interior/saqer 54/Untitled-7_result.webp";
import in32_img7 from "@/imgs/Interior/saqer 54/Untitled-8_result.webp";
import in32_img8 from "@/imgs/Interior/saqer 54/Untitled-9_result.webp";
import in32_img9 from "@/imgs/Interior/saqer 54/Untitled-10_result.webp";
import in32_img10 from "@/imgs/Interior/saqer 54/Untitled-11_result.webp";
import in32_img11 from "@/imgs/Interior/saqer 54/Untitled-12_result.webp";

export const images: StaticImageData[] = [in32_img0, in32_img1, in32_img2, in32_img3, in32_img4, in32_img5, in32_img6, in32_img7, in32_img8, in32_img9, in32_img10, in32_img11];
