/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in33_img0 from "@/imgs/Interior/saqer 55/oday_result.webp";
import in33_img1 from "@/imgs/Interior/saqer 55/Corona Camera001 copy_result.webp";
import in33_img2 from "@/imgs/Interior/saqer 55/Corona Camera002 copy_result.webp";
import in33_img3 from "@/imgs/Interior/saqer 55/Corona Camera003 copy_result.webp";
import in33_img4 from "@/imgs/Interior/saqer 55/Corona Camera005 copy_result.webp";
import in33_img5 from "@/imgs/Interior/saqer 55/Corona Camera006 copy_result.webp";
import in33_img6 from "@/imgs/Interior/saqer 55/Corona Camera007 copy_result.webp";
import in33_img7 from "@/imgs/Interior/saqer 55/Corona Camera008 copy_result.webp";
import in33_img8 from "@/imgs/Interior/saqer 55/Corona Camera009 copy_result.webp";

export const images: StaticImageData[] = [in33_img0, in33_img1, in33_img2, in33_img3, in33_img4, in33_img5, in33_img6, in33_img7, in33_img8];
