/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in35_img0 from "@/imgs/Interior/tarifi apartment 61/oday_result.webp";
import in35_img1 from "@/imgs/Interior/tarifi apartment 61/3 copy_result.webp";
import in35_img2 from "@/imgs/Interior/tarifi apartment 61/4 copy_result.webp";
import in35_img3 from "@/imgs/Interior/tarifi apartment 61/12 copy_result.webp";
import in35_img4 from "@/imgs/Interior/tarifi apartment 61/C2 copy_result.webp";
import in35_img5 from "@/imgs/Interior/tarifi apartment 61/C3 copy_result.webp";
import in35_img6 from "@/imgs/Interior/tarifi apartment 61/C4 copy_result.webp";
import in35_img7 from "@/imgs/Interior/tarifi apartment 61/C5 copy_result.webp";
import in35_img8 from "@/imgs/Interior/tarifi apartment 61/C6 copy_result.webp";
import in35_img9 from "@/imgs/Interior/tarifi apartment 61/C7 copy_result.webp";
import in35_img10 from "@/imgs/Interior/tarifi apartment 61/C8 copy_result.webp";
import in35_img11 from "@/imgs/Interior/tarifi apartment 61/C9 copy_result.webp";
import in35_img12 from "@/imgs/Interior/tarifi apartment 61/c10 copy_result.webp";
import in35_img13 from "@/imgs/Interior/tarifi apartment 61/c11 copy_result.webp";

export const images: StaticImageData[] = [in35_img0, in35_img1, in35_img2, in35_img3, in35_img4, in35_img5, in35_img6, in35_img7, in35_img8, in35_img9, in35_img10, in35_img11, in35_img12, in35_img13];
