/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-interior-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import in34_img0 from "@/imgs/Interior/tarifi 59/oday_result.webp";
import in34_img1 from "@/imgs/Interior/tarifi 59/1 copy_result.webp";
import in34_img2 from "@/imgs/Interior/tarifi 59/1_result.webp";
import in34_img3 from "@/imgs/Interior/tarifi 59/2_result.webp";
import in34_img4 from "@/imgs/Interior/tarifi 59/3 copy_result.webp";
import in34_img5 from "@/imgs/Interior/tarifi 59/3_result.webp";
import in34_img6 from "@/imgs/Interior/tarifi 59/4_result.webp";
import in34_img7 from "@/imgs/Interior/tarifi 59/5 copy_result.webp";
import in34_img8 from "@/imgs/Interior/tarifi 59/6 copy_result.webp";
import in34_img9 from "@/imgs/Interior/tarifi 59/7 copy_result.webp";
import in34_img10 from "@/imgs/Interior/tarifi 59/8 copy_result.webp";
import in34_img11 from "@/imgs/Interior/tarifi 59/9 copy_result.webp";
import in34_img12 from "@/imgs/Interior/tarifi 59/10 copy_result.webp";
import in34_img13 from "@/imgs/Interior/tarifi 59/11 copy_result.webp";
import in34_img14 from "@/imgs/Interior/tarifi 59/12 copy_result.webp";
import in34_img15 from "@/imgs/Interior/tarifi 59/13 copy_result.webp";
import in34_img16 from "@/imgs/Interior/tarifi 59/14 copy_result.webp";
import in34_img17 from "@/imgs/Interior/tarifi 59/15 copy_result.webp";
import in34_img18 from "@/imgs/Interior/tarifi 59/16 copy_result.webp";
import in34_img19 from "@/imgs/Interior/tarifi 59/18 copy_result.webp";
import in34_img20 from "@/imgs/Interior/tarifi 59/19 copy_result.webp";

export const images: StaticImageData[] = [in34_img0, in34_img1, in34_img2, in34_img3, in34_img4, in34_img5, in34_img6, in34_img7, in34_img8, in34_img9, in34_img10, in34_img11, in34_img12, in34_img13, in34_img14, in34_img15, in34_img16, in34_img17, in34_img18, in34_img19, in34_img20];
