/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-landscape-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ls5_img0 from "@/imgs/Exterior/landscape/nibal school 46/oday_result.webp";
import ls5_img1 from "@/imgs/Exterior/landscape/nibal school 46/250414 Nibal school-Model copy_result.webp";
import ls5_img2 from "@/imgs/Exterior/landscape/nibal school 46/250414 Nibal school-Model11_result.webp";
import ls5_img3 from "@/imgs/Exterior/landscape/nibal school 46/ديتليز_result.webp";
import ls5_img4 from "@/imgs/Exterior/landscape/nibal school 46/consept copy_result.webp";
import ls5_img5 from "@/imgs/Exterior/landscape/nibal school 46/D1+ copy_result.webp";
import ls5_img6 from "@/imgs/Exterior/landscape/nibal school 46/ISO1 copy_result.webp";
import ls5_img7 from "@/imgs/Exterior/landscape/nibal school 46/LAYER copy_result.webp";
import ls5_img8 from "@/imgs/Exterior/landscape/nibal school 46/poster 2_result.webp";
import ls5_img9 from "@/imgs/Exterior/landscape/nibal school 46/shot 1 copy_result.webp";
import ls5_img10 from "@/imgs/Exterior/landscape/nibal school 46/shot 2 copy_result.webp";
import ls5_img11 from "@/imgs/Exterior/landscape/nibal school 46/shot 4 copy_result.webp";

export const images: StaticImageData[] = [ls5_img0, ls5_img1, ls5_img2, ls5_img3, ls5_img4, ls5_img5, ls5_img6, ls5_img7, ls5_img8, ls5_img9, ls5_img10, ls5_img11];
