/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-landscape-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ls3_img0 from "@/imgs/Exterior/landscape/khan ahmar 33/oday_result.webp";
import ls3_img1 from "@/imgs/Exterior/landscape/khan ahmar 33/0.0_result.webp";
import ls3_img2 from "@/imgs/Exterior/landscape/khan ahmar 33/0.1_result.webp";
import ls3_img3 from "@/imgs/Exterior/landscape/khan ahmar 33/0.2_result.webp";
import ls3_img4 from "@/imgs/Exterior/landscape/khan ahmar 33/0.5_result.webp";
import ls3_img5 from "@/imgs/Exterior/landscape/khan ahmar 33/0.6_result.webp";
import ls3_img6 from "@/imgs/Exterior/landscape/khan ahmar 33/0.7_result.webp";

export const images: StaticImageData[] = [ls3_img0, ls3_img1, ls3_img2, ls3_img3, ls3_img4, ls3_img5, ls3_img6];
