/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-landscape-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ls6_img0 from "@/imgs/Exterior/landscape/shalabi 56/oday_result.webp";
import ls6_img1 from "@/imgs/Exterior/landscape/shalabi 56/A2_result.webp";
import ls6_img2 from "@/imgs/Exterior/landscape/shalabi 56/A3_result.webp";
import ls6_img3 from "@/imgs/Exterior/landscape/shalabi 56/A4_result.webp";
import ls6_img4 from "@/imgs/Exterior/landscape/shalabi 56/A5_result.webp";
import ls6_img5 from "@/imgs/Exterior/landscape/shalabi 56/A6_result.webp";
import ls6_img6 from "@/imgs/Exterior/landscape/shalabi 56/A8_result.webp";

export const images: StaticImageData[] = [ls6_img0, ls6_img1, ls6_img2, ls6_img3, ls6_img4, ls6_img5, ls6_img6];
