/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-landscape-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ls4_img0 from "@/imgs/Exterior/landscape/mohammad ram 40/oday_result.webp";
import ls4_img1 from "@/imgs/Exterior/landscape/mohammad ram 40/1 copy_result.webp";
import ls4_img2 from "@/imgs/Exterior/landscape/mohammad ram 40/2 copy_result.webp";
import ls4_img3 from "@/imgs/Exterior/landscape/mohammad ram 40/3 copy_result.webp";
import ls4_img4 from "@/imgs/Exterior/landscape/mohammad ram 40/5 copy_result.webp";
import ls4_img5 from "@/imgs/Exterior/landscape/mohammad ram 40/6 copy_result.webp";
import ls4_img6 from "@/imgs/Exterior/landscape/mohammad ram 40/7 copy_result.webp";
import ls4_img7 from "@/imgs/Exterior/landscape/mohammad ram 40/11 copy_result.webp";
import ls4_img8 from "@/imgs/Exterior/landscape/mohammad ram 40/12 copy_result.webp";
import ls4_img9 from "@/imgs/Exterior/landscape/mohammad ram 40/13 copy_result.webp";

export const images: StaticImageData[] = [ls4_img0, ls4_img1, ls4_img2, ls4_img3, ls4_img4, ls4_img5, ls4_img6, ls4_img7, ls4_img8, ls4_img9];
