/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-landscape-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ls2_img0 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/ODAY_result.webp";
import ls2_img1 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/1_result.webp";
import ls2_img2 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/4_result.webp";
import ls2_img3 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74701_result.webp";
import ls2_img4 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74702_result.webp";
import ls2_img5 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74703_result.webp";
import ls2_img6 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74704_result.webp";
import ls2_img7 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74706_result.webp";

export const images: StaticImageData[] = [ls2_img0, ls2_img1, ls2_img2, ls2_img3, ls2_img4, ls2_img5, ls2_img6, ls2_img7];
