/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-landscape-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ls0_img0 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/ODAY_result.webp";
import ls0_img1 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/1 copy_result.webp";
import ls0_img2 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/7 copy_result.webp";
import ls0_img3 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/9 copy_result.webp";
import ls0_img4 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/13 copy_result.webp";
import ls0_img5 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/15 copy_result.webp";

export const images: StaticImageData[] = [ls0_img0, ls0_img1, ls0_img2, ls0_img3, ls0_img4, ls0_img5];
