/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-landscape-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ls1_img0 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/ODAY_result.webp";
import ls1_img1 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/1 copy_result.webp";
import ls1_img2 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/2 copy 2_result.webp";
import ls1_img3 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/2 copy_result.webp";
import ls1_img4 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/4 copy_result.webp";
import ls1_img5 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/7 copy_result.webp";
import ls1_img6 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/9 copy_result.webp";
import ls1_img7 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/15 copy_result.webp";
import ls1_img8 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/17 copy_result.webp";

export const images: StaticImageData[] = [ls1_img0, ls1_img1, ls1_img2, ls1_img3, ls1_img4, ls1_img5, ls1_img6, ls1_img7, ls1_img8];
