/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-residential-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import rb1_img0 from "@/imgs/Exterior/residential building/awad allah  6/ODAY_result.webp";
import rb1_img1 from "@/imgs/Exterior/residential building/awad allah  6/10_result.webp";
import rb1_img2 from "@/imgs/Exterior/residential building/awad allah  6/a1_result.webp";
import rb1_img3 from "@/imgs/Exterior/residential building/awad allah  6/a2_result.webp";
import rb1_img4 from "@/imgs/Exterior/residential building/awad allah  6/a4_result.webp";
import rb1_img5 from "@/imgs/Exterior/residential building/awad allah  6/a6_result.webp";
import rb1_img6 from "@/imgs/Exterior/residential building/awad allah  6/a10_result.webp";
import rb1_img7 from "@/imgs/Exterior/residential building/awad allah  6/a11_result.webp";

export const images: StaticImageData[] = [rb1_img0, rb1_img1, rb1_img2, rb1_img3, rb1_img4, rb1_img5, rb1_img6, rb1_img7];
