/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-residential-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import rb7_img0 from "@/imgs/Exterior/residential building/zz hag 1213 08/ODAY_result.webp";
import rb7_img1 from "@/imgs/Exterior/residential building/zz hag 1213 08/1_result.webp";
import rb7_img2 from "@/imgs/Exterior/residential building/zz hag 1213 08/2_result.webp";
import rb7_img3 from "@/imgs/Exterior/residential building/zz hag 1213 08/3_result.webp";
import rb7_img4 from "@/imgs/Exterior/residential building/zz hag 1213 08/4_result.webp";
import rb7_img5 from "@/imgs/Exterior/residential building/zz hag 1213 08/5_result.webp";
import rb7_img6 from "@/imgs/Exterior/residential building/zz hag 1213 08/6_result.webp";
import rb7_img7 from "@/imgs/Exterior/residential building/zz hag 1213 08/7_result.webp";
import rb7_img8 from "@/imgs/Exterior/residential building/zz hag 1213 08/8_result.webp";
import rb7_img9 from "@/imgs/Exterior/residential building/zz hag 1213 08/9_result.webp";

export const images: StaticImageData[] = [rb7_img0, rb7_img1, rb7_img2, rb7_img3, rb7_img4, rb7_img5, rb7_img6, rb7_img7, rb7_img8, rb7_img9];
