/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-residential-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import rb3_img0 from "@/imgs/Exterior/residential building/hamada 26/ODAY_result.webp";
import rb3_img1 from "@/imgs/Exterior/residential building/hamada 26/1 (2)_result.webp";
import rb3_img2 from "@/imgs/Exterior/residential building/hamada 26/1 (3)_result.webp";
import rb3_img3 from "@/imgs/Exterior/residential building/hamada 26/1 (4)_result.webp";
import rb3_img4 from "@/imgs/Exterior/residential building/hamada 26/1 (5)_result.webp";
import rb3_img5 from "@/imgs/Exterior/residential building/hamada 26/1 (6)_result.webp";
import rb3_img6 from "@/imgs/Exterior/residential building/hamada 26/1 (7)_result.webp";
import rb3_img7 from "@/imgs/Exterior/residential building/hamada 26/1 (8)_result.webp";
import rb3_img8 from "@/imgs/Exterior/residential building/hamada 26/w_result.webp";

export const images: StaticImageData[] = [rb3_img0, rb3_img1, rb3_img2, rb3_img3, rb3_img4, rb3_img5, rb3_img6, rb3_img7, rb3_img8];
