/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-residential-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import rb5_img0 from "@/imgs/Exterior/residential building/ruba natsheh 51/oday_result.webp";
import rb5_img1 from "@/imgs/Exterior/residential building/ruba natsheh 51/1 copy_result.webp";
import rb5_img2 from "@/imgs/Exterior/residential building/ruba natsheh 51/2 copy_result.webp";
import rb5_img3 from "@/imgs/Exterior/residential building/ruba natsheh 51/3 copy_result.webp";
import rb5_img4 from "@/imgs/Exterior/residential building/ruba natsheh 51/4 copy_result.webp";
import rb5_img5 from "@/imgs/Exterior/residential building/ruba natsheh 51/7 copy_result.webp";
import rb5_img6 from "@/imgs/Exterior/residential building/ruba natsheh 51/9 copy_result.webp";
import rb5_img7 from "@/imgs/Exterior/residential building/ruba natsheh 51/10 copy_result.webp";
import rb5_img8 from "@/imgs/Exterior/residential building/ruba natsheh 51/12 copy_result.webp";

export const images: StaticImageData[] = [rb5_img0, rb5_img1, rb5_img2, rb5_img3, rb5_img4, rb5_img5, rb5_img6, rb5_img7, rb5_img8];
