/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-residential-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import rb4_img0 from "@/imgs/Exterior/residential building/luay jeris 35/oday_result.webp";
import rb4_img1 from "@/imgs/Exterior/residential building/luay jeris 35/A1_result.webp";
import rb4_img2 from "@/imgs/Exterior/residential building/luay jeris 35/A3_result.webp";
import rb4_img3 from "@/imgs/Exterior/residential building/luay jeris 35/A4_result.webp";
import rb4_img4 from "@/imgs/Exterior/residential building/luay jeris 35/A6_result.webp";
import rb4_img5 from "@/imgs/Exterior/residential building/luay jeris 35/B4_result.webp";
import rb4_img6 from "@/imgs/Exterior/residential building/luay jeris 35/E1_result.webp";

export const images: StaticImageData[] = [rb4_img0, rb4_img1, rb4_img2, rb4_img3, rb4_img4, rb4_img5, rb4_img6];
