/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-residential-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import rb2_img0 from "@/imgs/Exterior/residential building/hamada 25/ODAY_result.webp";
import rb2_img1 from "@/imgs/Exterior/residential building/hamada 25/magnific__enhance__87047_result.webp";
import rb2_img2 from "@/imgs/Exterior/residential building/hamada 25/magnific__enhance__87049_result.webp";

export const images: StaticImageData[] = [rb2_img0, rb2_img1, rb2_img2];
