/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-residential-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import rb6_img0 from "@/imgs/Exterior/residential building/zz ab building 07/ODAY_result.webp";
import rb6_img1 from "@/imgs/Exterior/residential building/zz ab building 07/1_result.webp";
import rb6_img2 from "@/imgs/Exterior/residential building/zz ab building 07/2_result.webp";
import rb6_img3 from "@/imgs/Exterior/residential building/zz ab building 07/3_result.webp";
import rb6_img4 from "@/imgs/Exterior/residential building/zz ab building 07/4_result.webp";
import rb6_img5 from "@/imgs/Exterior/residential building/zz ab building 07/5_result.webp";
import rb6_img6 from "@/imgs/Exterior/residential building/zz ab building 07/6_result.webp";
import rb6_img7 from "@/imgs/Exterior/residential building/zz ab building 07/7_result.webp";

export const images: StaticImageData[] = [rb6_img0, rb6_img1, rb6_img2, rb6_img3, rb6_img4, rb6_img5, rb6_img6, rb6_img7];
