/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-residential-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import rb0_img0 from "@/imgs/Exterior/residential building/abu kareem 1/ODAY_result.webp";
import rb0_img1 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__-__36922_result.webp";
import rb0_img2 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__1876_result.webp";
import rb0_img3 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__9977_result.webp";
import rb0_img4 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__10229_result.webp";
import rb0_img5 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__22746_result.webp";
import rb0_img6 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__36088_result.webp";
import rb0_img7 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__60862_result.webp";
import rb0_img8 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__70275_result.webp";
import rb0_img9 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__71958_result.webp";
import rb0_img10 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__88226_result.webp";
import rb0_img11 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__88996_result.webp";
import rb0_img12 from "@/imgs/Exterior/residential building/abu kareem 1/freepik__enhance__95458_result.webp";

export const images: StaticImageData[] = [rb0_img0, rb0_img1, rb0_img2, rb0_img3, rb0_img4, rb0_img5, rb0_img6, rb0_img7, rb0_img8, rb0_img9, rb0_img10, rb0_img11, rb0_img12];
