/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil3_img0 from "@/imgs/Exterior/Villa/dr salah villa V 18/ODAY_result.webp";
import vil3_img1 from "@/imgs/Exterior/Villa/dr salah villa V 18/a5_result.webp";
import vil3_img2 from "@/imgs/Exterior/Villa/dr salah villa V 18/a15_result.webp";
import vil3_img3 from "@/imgs/Exterior/Villa/dr salah villa V 18/b4_result.webp";
import vil3_img4 from "@/imgs/Exterior/Villa/dr salah villa V 18/b7_result.webp";

export const images: StaticImageData[] = [vil3_img0, vil3_img1, vil3_img2, vil3_img3, vil3_img4];
