/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil12_img0 from "@/imgs/Exterior/Villa/villa taim/oday.jpeg";
import vil12_img1 from "@/imgs/Exterior/Villa/villa taim/magnific_.-._jU6hTtdLD0.jpeg";
import vil12_img2 from "@/imgs/Exterior/Villa/villa taim/magnific_enhance-details_6AMrvZQiJO.jpeg";
import vil12_img3 from "@/imgs/Exterior/Villa/villa taim/magnific_enhance-details_aFjc4oEfSh.jpeg";
import vil12_img4 from "@/imgs/Exterior/Villa/villa taim/magnific_enhance-details_dtF3jhpXSL.jpeg";
import vil12_img5 from "@/imgs/Exterior/Villa/villa taim/magnific_enhance-details_mE1nOjUhJQ.jpeg";
import vil12_img6 from "@/imgs/Exterior/Villa/villa taim/magnific_inhance-details_cphOuuW0eP.jpeg";

export const images: StaticImageData[] = [vil12_img0, vil12_img1, vil12_img2, vil12_img3, vil12_img4, vil12_img5, vil12_img6];
