/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil2_img0 from "@/imgs/Exterior/Villa/dr baha 14/ODAY_result.webp";
import vil2_img1 from "@/imgs/Exterior/Villa/dr baha 14/11_result.webp";
import vil2_img2 from "@/imgs/Exterior/Villa/dr baha 14/12_result.webp";
import vil2_img3 from "@/imgs/Exterior/Villa/dr baha 14/13_result.webp";
import vil2_img4 from "@/imgs/Exterior/Villa/dr baha 14/a11_result.webp";
import vil2_img5 from "@/imgs/Exterior/Villa/dr baha 14/a12_result.webp";
import vil2_img6 from "@/imgs/Exterior/Villa/dr baha 14/a13_result.webp";

export const images: StaticImageData[] = [vil2_img0, vil2_img1, vil2_img2, vil2_img3, vil2_img4, vil2_img5, vil2_img6];
