/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil5_img0 from "@/imgs/Exterior/Villa/nasim shawahneh 42/oday_result.webp";
import vil5_img1 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33170_result.webp";
import vil5_img2 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33180_result.webp";
import vil5_img3 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33181_result.webp";
import vil5_img4 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33183_result.webp";
import vil5_img5 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__4622_result.webp";
import vil5_img6 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33165_result.webp";
import vil5_img7 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33168_result.webp";
import vil5_img8 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33172_result.webp";
import vil5_img9 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33175_result.webp";
import vil5_img10 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33177_result.webp";
import vil5_img11 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__71855_result.webp";
import vil5_img12 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__99477_result.webp";

export const images: StaticImageData[] = [vil5_img0, vil5_img1, vil5_img2, vil5_img3, vil5_img4, vil5_img5, vil5_img6, vil5_img7, vil5_img8, vil5_img9, vil5_img10, vil5_img11, vil5_img12];
