/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil10_img0 from "@/imgs/Exterior/Villa/villa 11 vi12/ODAY_result.webp";
import vil10_img1 from "@/imgs/Exterior/Villa/villa 11 vi12/1_result.webp";
import vil10_img2 from "@/imgs/Exterior/Villa/villa 11 vi12/2_result.webp";
import vil10_img3 from "@/imgs/Exterior/Villa/villa 11 vi12/3_result.webp";
import vil10_img4 from "@/imgs/Exterior/Villa/villa 11 vi12/4_result.webp";

export const images: StaticImageData[] = [vil10_img0, vil10_img1, vil10_img2, vil10_img3, vil10_img4];
