/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil4_img0 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/ODAY_result.webp";
import vil4_img1 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/8 copy_result.webp";
import vil4_img2 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/9 copy_result.webp";
import vil4_img3 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/10 copy_result.webp";
import vil4_img4 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/11 copy_result.webp";
import vil4_img5 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/12 copy_result.webp";
import vil4_img6 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/13 copy_result.webp";
import vil4_img7 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/14 copy_result.webp";
import vil4_img8 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/15 copy_result.webp";
import vil4_img9 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/17 copy_result.webp";
import vil4_img10 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/18 copy_result.webp";
import vil4_img11 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/19 copy_result.webp";
import vil4_img12 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/20 copy (1)_result.webp";
import vil4_img13 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/21 copy_result.webp";
import vil4_img14 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/23 copy_result.webp";
import vil4_img15 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/24 copy_result.webp";
import vil4_img16 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/25 copy_result.webp";
import vil4_img17 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/26 copy_result.webp";
import vil4_img18 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/27 copy_result.webp";
import vil4_img19 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/30 copy_result.webp";
import vil4_img20 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/31 copy_result.webp";
import vil4_img21 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/32 copy_result.webp";
import vil4_img22 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/33 copy_result.webp";
import vil4_img23 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/35 copy_result.webp";
import vil4_img24 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/36 copy_result.webp";
import vil4_img25 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/37 copy_result.webp";
import vil4_img26 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/38 copy_result.webp";
import vil4_img27 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/39 copy_result.webp";
import vil4_img28 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/40 copy_result.webp";
import vil4_img29 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/41 copy_result.webp";
import vil4_img30 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/42 copy_result.webp";

export const images: StaticImageData[] = [vil4_img0, vil4_img1, vil4_img2, vil4_img3, vil4_img4, vil4_img5, vil4_img6, vil4_img7, vil4_img8, vil4_img9, vil4_img10, vil4_img11, vil4_img12, vil4_img13, vil4_img14, vil4_img15, vil4_img16, vil4_img17, vil4_img18, vil4_img19, vil4_img20, vil4_img21, vil4_img22, vil4_img23, vil4_img24, vil4_img25, vil4_img26, vil4_img27, vil4_img28, vil4_img29, vil4_img30];
