/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil6_img0 from "@/imgs/Exterior/Villa/nasser jericho 43/oday_result.webp";
import vil6_img1 from "@/imgs/Exterior/Villa/nasser jericho 43/1_result.webp";
import vil6_img2 from "@/imgs/Exterior/Villa/nasser jericho 43/2_result.webp";
import vil6_img3 from "@/imgs/Exterior/Villa/nasser jericho 43/3_result.webp";
import vil6_img4 from "@/imgs/Exterior/Villa/nasser jericho 43/4_result.webp";
import vil6_img5 from "@/imgs/Exterior/Villa/nasser jericho 43/5_result.webp";
import vil6_img6 from "@/imgs/Exterior/Villa/nasser jericho 43/7_result.webp";
import vil6_img7 from "@/imgs/Exterior/Villa/nasser jericho 43/9_result.webp";
import vil6_img8 from "@/imgs/Exterior/Villa/nasser jericho 43/10_result.webp";
import vil6_img9 from "@/imgs/Exterior/Villa/nasser jericho 43/12_result.webp";
import vil6_img10 from "@/imgs/Exterior/Villa/nasser jericho 43/13_result.webp";

export const images: StaticImageData[] = [vil6_img0, vil6_img1, vil6_img2, vil6_img3, vil6_img4, vil6_img5, vil6_img6, vil6_img7, vil6_img8, vil6_img9, vil6_img10];
