/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil0_img0 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/ODAY_result.webp";
import vil0_img1 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/119993894_4057531554273742_2501635177429446388_n_result.webp";
import vil0_img2 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120061019_4057531184273779_5895088966008098218_n_result.webp";
import vil0_img3 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120085060_4057530944273803_3497870258245948265_n_result.webp";
import vil0_img4 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120087811_4057531874273710_3885943795715893720_n_result.webp";
import vil0_img5 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120153580_4057531694273728_2443758749108819940_n_result.webp";

export const images: StaticImageData[] = [vil0_img0, vil0_img1, vil0_img2, vil0_img3, vil0_img4, vil0_img5];
