/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil8_img0 from "@/imgs/Exterior/Villa/tareq fifil 58/oday_result.webp";
import vil8_img1 from "@/imgs/Exterior/Villa/tareq fifil 58/1_result.webp";
import vil8_img2 from "@/imgs/Exterior/Villa/tareq fifil 58/2_result.webp";
import vil8_img3 from "@/imgs/Exterior/Villa/tareq fifil 58/3_result.webp";
import vil8_img4 from "@/imgs/Exterior/Villa/tareq fifil 58/4_result.webp";
import vil8_img5 from "@/imgs/Exterior/Villa/tareq fifil 58/5_result.webp";
import vil8_img6 from "@/imgs/Exterior/Villa/tareq fifil 58/6_result.webp";
import vil8_img7 from "@/imgs/Exterior/Villa/tareq fifil 58/7_result.webp";
import vil8_img8 from "@/imgs/Exterior/Villa/tareq fifil 58/8_result.webp";
import vil8_img9 from "@/imgs/Exterior/Villa/tareq fifil 58/9_result.webp";
import vil8_img10 from "@/imgs/Exterior/Villa/tareq fifil 58/13_result.webp";
import vil8_img11 from "@/imgs/Exterior/Villa/tareq fifil 58/14_result.webp";
import vil8_img12 from "@/imgs/Exterior/Villa/tareq fifil 58/16_result.webp";
import vil8_img13 from "@/imgs/Exterior/Villa/tareq fifil 58/17_result.webp";

export const images: StaticImageData[] = [vil8_img0, vil8_img1, vil8_img2, vil8_img3, vil8_img4, vil8_img5, vil8_img6, vil8_img7, vil8_img8, vil8_img9, vil8_img10, vil8_img11, vil8_img12, vil8_img13];
