/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil9_img0 from "@/imgs/Exterior/Villa/villa 10 viv/ODAY_result.webp";
import vil9_img1 from "@/imgs/Exterior/Villa/villa 10 viv/1_result.webp";
import vil9_img2 from "@/imgs/Exterior/Villa/villa 10 viv/2_result.webp";
import vil9_img3 from "@/imgs/Exterior/Villa/villa 10 viv/3_result.webp";
import vil9_img4 from "@/imgs/Exterior/Villa/villa 10 viv/4_result.webp";
import vil9_img5 from "@/imgs/Exterior/Villa/villa 10 viv/5_result.webp";

export const images: StaticImageData[] = [vil9_img0, vil9_img1, vil9_img2, vil9_img3, vil9_img4, vil9_img5];
