/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil1_img0 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/ODAY_result.webp";
import vil1_img1 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/3 copy_result.webp";
import vil1_img2 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/6 copy_result.webp";
import vil1_img3 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/7 copy_result.webp";
import vil1_img4 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/8 copy_result.webp";
import vil1_img5 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/10 copy_result.webp";
import vil1_img6 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/11 copy_result.webp";
import vil1_img7 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/12 copy_result.webp";
import vil1_img8 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/13 copy_result.webp";
import vil1_img9 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/14 copy_result.webp";
import vil1_img10 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/15 copy_result.webp";
import vil1_img11 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/17 copy_result.webp";

export const images: StaticImageData[] = [vil1_img0, vil1_img1, vil1_img2, vil1_img3, vil1_img4, vil1_img5, vil1_img6, vil1_img7, vil1_img8, vil1_img9, vil1_img10, vil1_img11];
