/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil11_img0 from "@/imgs/Exterior/Villa/villa 12 bh/ODAY_result.webp";
import vil11_img1 from "@/imgs/Exterior/Villa/villa 12 bh/1_result.webp";
import vil11_img2 from "@/imgs/Exterior/Villa/villa 12 bh/2_result.webp";
import vil11_img3 from "@/imgs/Exterior/Villa/villa 12 bh/3_result.webp";
import vil11_img4 from "@/imgs/Exterior/Villa/villa 12 bh/4_result.webp";
import vil11_img5 from "@/imgs/Exterior/Villa/villa 12 bh/5_result.webp";
import vil11_img6 from "@/imgs/Exterior/Villa/villa 12 bh/6_result.webp";
import vil11_img7 from "@/imgs/Exterior/Villa/villa 12 bh/7_result.webp";
import vil11_img8 from "@/imgs/Exterior/Villa/villa 12 bh/8_result.webp";

export const images: StaticImageData[] = [vil11_img0, vil11_img1, vil11_img2, vil11_img3, vil11_img4, vil11_img5, vil11_img6, vil11_img7, vil11_img8];
