/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil7_img0 from "@/imgs/Exterior/Villa/sofien fayek 57/oday_result.webp";
import vil7_img1 from "@/imgs/Exterior/Villa/sofien fayek 57/2_result.webp";
import vil7_img2 from "@/imgs/Exterior/Villa/sofien fayek 57/3_result.webp";
import vil7_img3 from "@/imgs/Exterior/Villa/sofien fayek 57/4_result.webp";
import vil7_img4 from "@/imgs/Exterior/Villa/sofien fayek 57/5_result.webp";
import vil7_img5 from "@/imgs/Exterior/Villa/sofien fayek 57/6_result.webp";
import vil7_img6 from "@/imgs/Exterior/Villa/sofien fayek 57/10_result.webp";
import vil7_img7 from "@/imgs/Exterior/Villa/sofien fayek 57/11_result.webp";

export const images: StaticImageData[] = [vil7_img0, vil7_img1, vil7_img2, vil7_img3, vil7_img4, vil7_img5, vil7_img6, vil7_img7];
