/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-cottage-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ct0_img0 from "@/imgs/Exterior/Cottage/amer abu hamdieh 5/ODAY_result.webp";
import ct0_img1 from "@/imgs/Exterior/Cottage/amer abu hamdieh 5/1_result.webp";
import ct0_img2 from "@/imgs/Exterior/Cottage/amer abu hamdieh 5/3_result.webp";
import ct0_img3 from "@/imgs/Exterior/Cottage/amer abu hamdieh 5/5_result.webp";
import ct1_img0 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/ODAY_result.webp";
import ct1_img1 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/2 copy_result.webp";
import ct1_img2 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/4 copy_result.webp";
import ct1_img3 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/5 copy_result.webp";
import ct1_img4 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/6 copy_result.webp";
import ct1_img5 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/7 copy_result.webp";
import ct1_img6 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/8 copy_result.webp";
import ct1_img7 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/9 copy_result.webp";
import ct1_img8 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/10 copy_result.webp";
import ct1_img9 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/11 copy_result.webp";
import ct1_img10 from "@/imgs/Exterior/Cottage/COTATGE ADAM 12/12 copy_result.webp";
import ct2_img0 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/oday_result.webp";
import ct2_img1 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-2_result.webp";
import ct2_img2 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-3_result.webp";
import ct2_img3 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-4_result.webp";
import ct2_img4 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-5_result.webp";
import ct2_img5 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-6_result.webp";
import ct2_img6 from "@/imgs/Exterior/Cottage/mahdi abu shariif 36/Untitled-7_result.webp";
import ct3_img0 from "@/imgs/Exterior/Cottage/majed cottage 37/oday_result.webp";
import ct3_img1 from "@/imgs/Exterior/Cottage/majed cottage 37/2_result.webp";
import ct3_img2 from "@/imgs/Exterior/Cottage/majed cottage 37/3_result.webp";
import ct3_img3 from "@/imgs/Exterior/Cottage/majed cottage 37/4_result.webp";
import ct3_img4 from "@/imgs/Exterior/Cottage/majed cottage 37/5_result.webp";
import ct3_img5 from "@/imgs/Exterior/Cottage/majed cottage 37/7_result.webp";
import ct3_img6 from "@/imgs/Exterior/Cottage/majed cottage 37/8_result.webp";
import ct3_img7 from "@/imgs/Exterior/Cottage/majed cottage 37/9_result.webp";
import ct3_img8 from "@/imgs/Exterior/Cottage/majed cottage 37/12_result.webp";
import ct3_img9 from "@/imgs/Exterior/Cottage/majed cottage 37/13_result.webp";
import ct3_img10 from "@/imgs/Exterior/Cottage/majed cottage 37/14_result.webp";
import ct3_img11 from "@/imgs/Exterior/Cottage/majed cottage 37/16_result.webp";

export const cottageProjects = [
  {
    id: "cot-amer-abu-hamdieh-5",
    orderLabel: "01",
    title: "COTTAGE 1",
    country: "Not specified",
    tag: "Cottage Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "cottage" as const,
    projectType: "Cottage",
    year: "2019",
    area: "380 m²",
    concept: "A charming cottage designed to blend naturally with its sloped landscape through a warm, human-scaled composition. The project combines pitched-roof volumes, welcoming terraces, and landscaped outdoor spaces to create a peaceful retreat with a strong connection to its surroundings.",
    styleMaterials: "Rustic Mediterranean style with light natural stone façades, dark pitched-tile roofs, warm wood trim, arched windows and doors, dark metal railings, stone retaining walls, traditional lanterns, and carefully landscaped gardens.",
    image: ct0_img0,
    imageAlt: "COTTAGE 1 — exterior visualization",
  },
  {
    id: "cot-cotatge-adam-12",
    orderLabel: "02",
    title: "ADAM'S COTTAGE",
    country: "Surda, Ramallah, Palestine",
    tag: "Cottage Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "cottage" as const,
    projectType: "Cottage",
    year: "2021",
    area: "50 m²",
    concept: "A contemporary garden cottage designed as a private retreat immersed in nature. The compact pavilion opens onto a landscaped courtyard with a sunken outdoor seating area, creating a seamless connection between the interior spaces, the garden, and the surrounding landscape.",
    styleMaterials: "Contemporary minimalist style with natural stone walls, warm wood cladding, a low-profile roof, expansive glass openings, dark metal frames, integrated linear lighting, landscaped gardens, and a sunken outdoor lounge with a central fire feature.",
    image: ct1_img0,
    imageAlt: "ADAM'S COTTAGE — exterior visualization",
  },
  {
    id: "cot-mahdi-abu-shariif-36",
    orderLabel: "03",
    title: "GEORGE COTTAGE",
    country: "Ramallah, Palestine",
    tag: "Cottage Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "cottage" as const,
    projectType: "Cottage",
    year: "2022",
    area: "390 m²",
    concept: "A warm and inviting cottage designed to blend naturally with its wooded setting and sloped landscape. The composition combines stone-clad volumes, pitched roofs, generous terraces, and large glazed openings to create a comfortable retreat with strong visual and physical connections to the surrounding garden.",
    styleMaterials: "Contemporary rustic style with natural stone façades, dark pitched-tile roofs, timber roof trim, expansive glass gables, dark metal railings, deep overhangs, stone retaining walls, landscaped gardens, and carefully integrated outdoor seating areas.",
    image: ct2_img0,
    imageAlt: "GEORGE COTTAGE — exterior visualization",
  },
  {
    id: "cot-majed-cottage-37",
    orderLabel: "04",
    title: "MAJED'S COTTAGE",
    country: "Ramallah, Palestine",
    tag: "Cottage Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "cottage" as const,
    projectType: "Cottage",
    year: "2022",
    area: "105 m²",
    concept: "A compact contemporary cottage designed as a peaceful retreat within a landscaped natural setting. The project uses a dynamic roof profile, double-height glazed spaces, and elevated outdoor terraces to create a sense of openness and maximize the connection with the surrounding garden.",
    styleMaterials: "Contemporary rustic style with light natural stone walls, dark metal roof edges, large glass openings, black metal structural details, glass balcony railings, a stone fireplace, landscaped gardens, and a shaded outdoor pergola.",
    image: ct3_img0,
    imageAlt: "MAJED'S COTTAGE — exterior visualization",
  },
];

const cottageGalleryById: Record<string, StaticImageData[]> = {
  ["cot-amer-abu-hamdieh-5"]: [ct0_img0, ct0_img1, ct0_img2, ct0_img3],
  ["cot-cotatge-adam-12"]: [ct1_img0, ct1_img1, ct1_img2, ct1_img3, ct1_img4, ct1_img5, ct1_img6, ct1_img7, ct1_img8, ct1_img9, ct1_img10],
  ["cot-mahdi-abu-shariif-36"]: [ct2_img0, ct2_img1, ct2_img2, ct2_img3, ct2_img4, ct2_img5, ct2_img6],
  ["cot-majed-cottage-37"]: [ct3_img0, ct3_img1, ct3_img2, ct3_img3, ct3_img4, ct3_img5, ct3_img6, ct3_img7, ct3_img8, ct3_img9, ct3_img10, ct3_img11],
};

export function getCottageProjectGalleryImages(projectId: string): StaticImageData[] | undefined {
  return cottageGalleryById[projectId];
}
