/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil0_img0 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/ODAY_result.webp";
import vil0_img1 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/119993894_4057531554273742_2501635177429446388_n_result.webp";
import vil0_img2 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120061019_4057531184273779_5895088966008098218_n_result.webp";
import vil0_img3 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120085060_4057530944273803_3497870258245948265_n_result.webp";
import vil0_img4 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120087811_4057531874273710_3885943795715893720_n_result.webp";
import vil0_img5 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120153580_4057531694273728_2443758749108819940_n_result.webp";
import vil1_img0 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/ODAY_result.webp";
import vil1_img1 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/3 copy_result.webp";
import vil1_img2 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/6 copy_result.webp";
import vil1_img3 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/7 copy_result.webp";
import vil1_img4 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/8 copy_result.webp";
import vil1_img5 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/10 copy_result.webp";
import vil1_img6 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/11 copy_result.webp";
import vil1_img7 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/12 copy_result.webp";
import vil1_img8 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/13 copy_result.webp";
import vil1_img9 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/14 copy_result.webp";
import vil1_img10 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/15 copy_result.webp";
import vil1_img11 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/17 copy_result.webp";
import vil2_img0 from "@/imgs/Exterior/Villa/dr baha 14/ODAY_result.webp";
import vil2_img1 from "@/imgs/Exterior/Villa/dr baha 14/11_result.webp";
import vil2_img2 from "@/imgs/Exterior/Villa/dr baha 14/12_result.webp";
import vil2_img3 from "@/imgs/Exterior/Villa/dr baha 14/13_result.webp";
import vil2_img4 from "@/imgs/Exterior/Villa/dr baha 14/a11_result.webp";
import vil2_img5 from "@/imgs/Exterior/Villa/dr baha 14/a12_result.webp";
import vil2_img6 from "@/imgs/Exterior/Villa/dr baha 14/a13_result.webp";
import vil3_img0 from "@/imgs/Exterior/Villa/dr salah villa V 18/ODAY_result.webp";
import vil3_img1 from "@/imgs/Exterior/Villa/dr salah villa V 18/a5_result.webp";
import vil3_img2 from "@/imgs/Exterior/Villa/dr salah villa V 18/a15_result.webp";
import vil3_img3 from "@/imgs/Exterior/Villa/dr salah villa V 18/b4_result.webp";
import vil3_img4 from "@/imgs/Exterior/Villa/dr salah villa V 18/b7_result.webp";
import vil4_img0 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/ODAY_result.webp";
import vil4_img1 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/8 copy_result.webp";
import vil4_img2 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/9 copy_result.webp";
import vil4_img3 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/10 copy_result.webp";
import vil4_img4 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/11 copy_result.webp";
import vil4_img5 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/12 copy_result.webp";
import vil4_img6 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/13 copy_result.webp";
import vil4_img7 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/14 copy_result.webp";
import vil4_img8 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/15 copy_result.webp";
import vil4_img9 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/17 copy_result.webp";
import vil4_img10 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/18 copy_result.webp";
import vil4_img11 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/19 copy_result.webp";
import vil4_img12 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/20 copy (1)_result.webp";
import vil4_img13 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/21 copy_result.webp";
import vil4_img14 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/23 copy_result.webp";
import vil4_img15 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/24 copy_result.webp";
import vil4_img16 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/25 copy_result.webp";
import vil4_img17 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/26 copy_result.webp";
import vil4_img18 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/27 copy_result.webp";
import vil4_img19 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/30 copy_result.webp";
import vil4_img20 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/31 copy_result.webp";
import vil4_img21 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/32 copy_result.webp";
import vil4_img22 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/33 copy_result.webp";
import vil4_img23 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/35 copy_result.webp";
import vil4_img24 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/36 copy_result.webp";
import vil4_img25 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/37 copy_result.webp";
import vil4_img26 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/38 copy_result.webp";
import vil4_img27 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/39 copy_result.webp";
import vil4_img28 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/40 copy_result.webp";
import vil4_img29 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/41 copy_result.webp";
import vil4_img30 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/42 copy_result.webp";
import vil5_img0 from "@/imgs/Exterior/Villa/nasim shawahneh 42/oday_result.webp";
import vil5_img1 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33170_result.webp";
import vil5_img2 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33180_result.webp";
import vil5_img3 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33181_result.webp";
import vil5_img4 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33183_result.webp";
import vil5_img5 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__4622_result.webp";
import vil5_img6 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33165_result.webp";
import vil5_img7 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33168_result.webp";
import vil5_img8 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33172_result.webp";
import vil5_img9 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33175_result.webp";
import vil5_img10 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33177_result.webp";
import vil5_img11 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__71855_result.webp";
import vil5_img12 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__99477_result.webp";
import vil6_img0 from "@/imgs/Exterior/Villa/nasser jericho 43/oday_result.webp";
import vil6_img1 from "@/imgs/Exterior/Villa/nasser jericho 43/1_result.webp";
import vil6_img2 from "@/imgs/Exterior/Villa/nasser jericho 43/2_result.webp";
import vil6_img3 from "@/imgs/Exterior/Villa/nasser jericho 43/3_result.webp";
import vil6_img4 from "@/imgs/Exterior/Villa/nasser jericho 43/4_result.webp";
import vil6_img5 from "@/imgs/Exterior/Villa/nasser jericho 43/5_result.webp";
import vil6_img6 from "@/imgs/Exterior/Villa/nasser jericho 43/7_result.webp";
import vil6_img7 from "@/imgs/Exterior/Villa/nasser jericho 43/9_result.webp";
import vil6_img8 from "@/imgs/Exterior/Villa/nasser jericho 43/10_result.webp";
import vil6_img9 from "@/imgs/Exterior/Villa/nasser jericho 43/12_result.webp";
import vil6_img10 from "@/imgs/Exterior/Villa/nasser jericho 43/13_result.webp";
import vil7_img0 from "@/imgs/Exterior/Villa/sofien fayek 57/oday_result.webp";
import vil7_img1 from "@/imgs/Exterior/Villa/sofien fayek 57/2_result.webp";
import vil7_img2 from "@/imgs/Exterior/Villa/sofien fayek 57/3_result.webp";
import vil7_img3 from "@/imgs/Exterior/Villa/sofien fayek 57/4_result.webp";
import vil7_img4 from "@/imgs/Exterior/Villa/sofien fayek 57/5_result.webp";
import vil7_img5 from "@/imgs/Exterior/Villa/sofien fayek 57/6_result.webp";
import vil7_img6 from "@/imgs/Exterior/Villa/sofien fayek 57/10_result.webp";
import vil7_img7 from "@/imgs/Exterior/Villa/sofien fayek 57/11_result.webp";
import vil8_img0 from "@/imgs/Exterior/Villa/tareq fifil 58/oday_result.webp";
import vil8_img1 from "@/imgs/Exterior/Villa/tareq fifil 58/1_result.webp";
import vil8_img2 from "@/imgs/Exterior/Villa/tareq fifil 58/2_result.webp";
import vil8_img3 from "@/imgs/Exterior/Villa/tareq fifil 58/3_result.webp";
import vil8_img4 from "@/imgs/Exterior/Villa/tareq fifil 58/4_result.webp";
import vil8_img5 from "@/imgs/Exterior/Villa/tareq fifil 58/5_result.webp";
import vil8_img6 from "@/imgs/Exterior/Villa/tareq fifil 58/6_result.webp";
import vil8_img7 from "@/imgs/Exterior/Villa/tareq fifil 58/7_result.webp";
import vil8_img8 from "@/imgs/Exterior/Villa/tareq fifil 58/8_result.webp";
import vil8_img9 from "@/imgs/Exterior/Villa/tareq fifil 58/9_result.webp";
import vil8_img10 from "@/imgs/Exterior/Villa/tareq fifil 58/13_result.webp";
import vil8_img11 from "@/imgs/Exterior/Villa/tareq fifil 58/14_result.webp";
import vil8_img12 from "@/imgs/Exterior/Villa/tareq fifil 58/16_result.webp";
import vil8_img13 from "@/imgs/Exterior/Villa/tareq fifil 58/17_result.webp";

export const villaProjects = [
  {
    id: "vil-abu-falah-2-option-villa-4",
    orderLabel: "01",
    title: "01",
    country: "Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    image: vil0_img0,
    imageAlt: "Villa 01 — exterior visualization",
  },
  {
    id: "vil-baha-hamdallah-8",
    orderLabel: "02",
    title: "02",
    country: "Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    image: vil1_img0,
    imageAlt: "Villa 02 — exterior visualization",
  },
  {
    id: "vil-dr-baha-14",
    orderLabel: "03",
    title: "03",
    country: "Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    image: vil2_img0,
    imageAlt: "Villa 03 — exterior visualization",
  },
  {
    id: "vil-dr-salah-villa-v-18",
    orderLabel: "04",
    title: "04",
    country: "Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    image: vil3_img0,
    imageAlt: "Villa 04 — exterior visualization",
  },
  {
    id: "vil-hassan-salameh-27",
    orderLabel: "05",
    title: "05",
    country: "Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    image: vil4_img0,
    imageAlt: "Villa 05 — exterior visualization",
  },
  {
    id: "vil-nasim-shawahneh-42",
    orderLabel: "06",
    title: "06",
    country: "Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    image: vil5_img0,
    imageAlt: "Villa 06 — exterior visualization",
  },
  {
    id: "vil-nasser-jericho-43",
    orderLabel: "07",
    title: "07",
    country: "Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    image: vil6_img0,
    imageAlt: "Villa 07 — exterior visualization",
  },
  {
    id: "vil-sofien-fayek-57",
    orderLabel: "08",
    title: "08",
    country: "Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    image: vil7_img0,
    imageAlt: "Villa 08 — exterior visualization",
  },
  {
    id: "vil-tareq-fifil-58",
    orderLabel: "09",
    title: "09",
    country: "Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    image: vil8_img0,
    imageAlt: "Villa 09 — exterior visualization",
  },
];

const villaGalleryById: Record<string, StaticImageData[]> = {
  ["vil-abu-falah-2-option-villa-4"]: [vil0_img0, vil0_img1, vil0_img2, vil0_img3, vil0_img4, vil0_img5],
  ["vil-baha-hamdallah-8"]: [vil1_img0, vil1_img1, vil1_img2, vil1_img3, vil1_img4, vil1_img5, vil1_img6, vil1_img7, vil1_img8, vil1_img9, vil1_img10, vil1_img11],
  ["vil-dr-baha-14"]: [vil2_img0, vil2_img1, vil2_img2, vil2_img3, vil2_img4, vil2_img5, vil2_img6],
  ["vil-dr-salah-villa-v-18"]: [vil3_img0, vil3_img1, vil3_img2, vil3_img3, vil3_img4],
  ["vil-hassan-salameh-27"]: [vil4_img0, vil4_img1, vil4_img2, vil4_img3, vil4_img4, vil4_img5, vil4_img6, vil4_img7, vil4_img8, vil4_img9, vil4_img10, vil4_img11, vil4_img12, vil4_img13, vil4_img14, vil4_img15, vil4_img16, vil4_img17, vil4_img18, vil4_img19, vil4_img20, vil4_img21, vil4_img22, vil4_img23, vil4_img24, vil4_img25, vil4_img26, vil4_img27, vil4_img28, vil4_img29, vil4_img30],
  ["vil-nasim-shawahneh-42"]: [vil5_img0, vil5_img1, vil5_img2, vil5_img3, vil5_img4, vil5_img5, vil5_img6, vil5_img7, vil5_img8, vil5_img9, vil5_img10, vil5_img11, vil5_img12],
  ["vil-nasser-jericho-43"]: [vil6_img0, vil6_img1, vil6_img2, vil6_img3, vil6_img4, vil6_img5, vil6_img6, vil6_img7, vil6_img8, vil6_img9, vil6_img10],
  ["vil-sofien-fayek-57"]: [vil7_img0, vil7_img1, vil7_img2, vil7_img3, vil7_img4, vil7_img5, vil7_img6, vil7_img7],
  ["vil-tareq-fifil-58"]: [vil8_img0, vil8_img1, vil8_img2, vil8_img3, vil8_img4, vil8_img5, vil8_img6, vil8_img7, vil8_img8, vil8_img9, vil8_img10, vil8_img11, vil8_img12, vil8_img13],
};

export function getVillaProjectGalleryImages(projectId: string): StaticImageData[] | undefined {
  return villaGalleryById[projectId];
}
