/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-residential-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

export const residentialGalleryLoaders: Record<
  string,
  () => Promise<StaticImageData[]>
> = {
  "res-abu-kareem-1": () => import("./generated-galleries/res-abu-kareem-1").then((m) => m.images),
  "res-awad-allah-6": () => import("./generated-galleries/res-awad-allah-6").then((m) => m.images),
  "res-hamada-25": () => import("./generated-galleries/res-hamada-25").then((m) => m.images),
  "res-hamada-26": () => import("./generated-galleries/res-hamada-26").then((m) => m.images),
  "res-luay-jeris-35": () => import("./generated-galleries/res-luay-jeris-35").then((m) => m.images),
  "res-ruba-natsheh-51": () => import("./generated-galleries/res-ruba-natsheh-51").then((m) => m.images),
  "res-zz-ab-building-07": () => import("./generated-galleries/res-zz-ab-building-07").then((m) => m.images),
  "res-zz-hag-1213-08": () => import("./generated-galleries/res-zz-hag-1213-08").then((m) => m.images),
};
