/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-cottage-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

export const cottageGalleryLoaders: Record<
  string,
  () => Promise<StaticImageData[]>
> = {
  "cot-amer-abu-hamdieh-5": () => import("./generated-galleries/cot-amer-abu-hamdieh-5").then((m) => m.images),
  "cot-cotatge-adam-12": () => import("./generated-galleries/cot-cotatge-adam-12").then((m) => m.images),
  "cot-mahdi-abu-shariif-36": () => import("./generated-galleries/cot-mahdi-abu-shariif-36").then((m) => m.images),
  "cot-majed-cottage-37": () => import("./generated-galleries/cot-majed-cottage-37").then((m) => m.images),
};
