/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-landscape-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ls0_img0 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/ODAY_result.webp";
import ls0_img1 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/1 copy_result.webp";
import ls0_img2 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/7 copy_result.webp";
import ls0_img3 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/9 copy_result.webp";
import ls0_img4 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/13 copy_result.webp";
import ls0_img5 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/15 copy_result.webp";
import ls1_img0 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/ODAY_result.webp";
import ls1_img1 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/1 copy_result.webp";
import ls1_img2 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/2 copy 2_result.webp";
import ls1_img3 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/2 copy_result.webp";
import ls1_img4 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/4 copy_result.webp";
import ls1_img5 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/7 copy_result.webp";
import ls1_img6 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/9 copy_result.webp";
import ls1_img7 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/15 copy_result.webp";
import ls1_img8 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/17 copy_result.webp";
import ls2_img0 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/ODAY_result.webp";
import ls2_img1 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/1_result.webp";
import ls2_img2 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/4_result.webp";
import ls2_img3 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74701_result.webp";
import ls2_img4 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74702_result.webp";
import ls2_img5 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74703_result.webp";
import ls2_img6 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74704_result.webp";
import ls2_img7 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74706_result.webp";
import ls3_img0 from "@/imgs/Exterior/landscape/khan ahmar 33/oday_result.webp";
import ls3_img1 from "@/imgs/Exterior/landscape/khan ahmar 33/0.0_result.webp";
import ls3_img2 from "@/imgs/Exterior/landscape/khan ahmar 33/0.1_result.webp";
import ls3_img3 from "@/imgs/Exterior/landscape/khan ahmar 33/0.2_result.webp";
import ls3_img4 from "@/imgs/Exterior/landscape/khan ahmar 33/0.5_result.webp";
import ls3_img5 from "@/imgs/Exterior/landscape/khan ahmar 33/0.6_result.webp";
import ls3_img6 from "@/imgs/Exterior/landscape/khan ahmar 33/0.7_result.webp";
import ls4_img0 from "@/imgs/Exterior/landscape/mohammad ram 40/oday_result.webp";
import ls4_img1 from "@/imgs/Exterior/landscape/mohammad ram 40/1 copy_result.webp";
import ls4_img2 from "@/imgs/Exterior/landscape/mohammad ram 40/2 copy_result.webp";
import ls4_img3 from "@/imgs/Exterior/landscape/mohammad ram 40/3 copy_result.webp";
import ls4_img4 from "@/imgs/Exterior/landscape/mohammad ram 40/5 copy_result.webp";
import ls4_img5 from "@/imgs/Exterior/landscape/mohammad ram 40/6 copy_result.webp";
import ls4_img6 from "@/imgs/Exterior/landscape/mohammad ram 40/7 copy_result.webp";
import ls4_img7 from "@/imgs/Exterior/landscape/mohammad ram 40/11 copy_result.webp";
import ls4_img8 from "@/imgs/Exterior/landscape/mohammad ram 40/12 copy_result.webp";
import ls4_img9 from "@/imgs/Exterior/landscape/mohammad ram 40/13 copy_result.webp";
import ls5_img0 from "@/imgs/Exterior/landscape/nibal school 46/oday_result.webp";
import ls5_img1 from "@/imgs/Exterior/landscape/nibal school 46/250414 Nibal school-Model copy_result.webp";
import ls5_img2 from "@/imgs/Exterior/landscape/nibal school 46/250414 Nibal school-Model11_result.webp";
import ls5_img3 from "@/imgs/Exterior/landscape/nibal school 46/ديتليز_result.webp";
import ls5_img4 from "@/imgs/Exterior/landscape/nibal school 46/consept copy_result.webp";
import ls5_img5 from "@/imgs/Exterior/landscape/nibal school 46/D1+ copy_result.webp";
import ls5_img6 from "@/imgs/Exterior/landscape/nibal school 46/ISO1 copy_result.webp";
import ls5_img7 from "@/imgs/Exterior/landscape/nibal school 46/LAYER copy_result.webp";
import ls5_img8 from "@/imgs/Exterior/landscape/nibal school 46/poster 2_result.webp";
import ls5_img9 from "@/imgs/Exterior/landscape/nibal school 46/shot 1 copy_result.webp";
import ls5_img10 from "@/imgs/Exterior/landscape/nibal school 46/shot 2 copy_result.webp";
import ls5_img11 from "@/imgs/Exterior/landscape/nibal school 46/shot 4 copy_result.webp";
import ls6_img0 from "@/imgs/Exterior/landscape/shalabi 56/oday_result.webp";
import ls6_img1 from "@/imgs/Exterior/landscape/shalabi 56/A2_result.webp";
import ls6_img2 from "@/imgs/Exterior/landscape/shalabi 56/A3_result.webp";
import ls6_img3 from "@/imgs/Exterior/landscape/shalabi 56/A4_result.webp";
import ls6_img4 from "@/imgs/Exterior/landscape/shalabi 56/A5_result.webp";
import ls6_img5 from "@/imgs/Exterior/landscape/shalabi 56/A6_result.webp";
import ls6_img6 from "@/imgs/Exterior/landscape/shalabi 56/A8_result.webp";

export const landscapeProjects = [
  {
    id: "lsc-ali-5alaf-rendering-classic-a3",
    orderLabel: "01",
    title: "01",
    country: "Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    image: ls0_img0,
    imageAlt: "Landscape 01 — design visualization",
  },
  {
    id: "lsc-ali-5alaf-rendering-modern-aa3",
    orderLabel: "02",
    title: "02",
    country: "Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    image: ls1_img0,
    imageAlt: "Landscape 02 — design visualization",
  },
  {
    id: "lsc-ghazi-el-bazzar-24",
    orderLabel: "03",
    title: "03",
    country: "Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    image: ls2_img0,
    imageAlt: "Landscape 03 — design visualization",
  },
  {
    id: "lsc-khan-ahmar-33",
    orderLabel: "04",
    title: "04",
    country: "Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    image: ls3_img0,
    imageAlt: "Landscape 04 — design visualization",
  },
  {
    id: "lsc-mohammad-ram-40",
    orderLabel: "05",
    title: "05",
    country: "Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    image: ls4_img0,
    imageAlt: "Landscape 05 — design visualization",
  },
  {
    id: "lsc-nibal-school-46",
    orderLabel: "06",
    title: "06",
    country: "Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    image: ls5_img0,
    imageAlt: "Landscape 06 — design visualization",
  },
  {
    id: "lsc-shalabi-56",
    orderLabel: "07",
    title: "07",
    country: "Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    image: ls6_img0,
    imageAlt: "Landscape 07 — design visualization",
  },
];

const landscapeGalleryById: Record<string, StaticImageData[]> = {
  ["lsc-ali-5alaf-rendering-classic-a3"]: [ls0_img0, ls0_img1, ls0_img2, ls0_img3, ls0_img4, ls0_img5],
  ["lsc-ali-5alaf-rendering-modern-aa3"]: [ls1_img0, ls1_img1, ls1_img2, ls1_img3, ls1_img4, ls1_img5, ls1_img6, ls1_img7, ls1_img8],
  ["lsc-ghazi-el-bazzar-24"]: [ls2_img0, ls2_img1, ls2_img2, ls2_img3, ls2_img4, ls2_img5, ls2_img6, ls2_img7],
  ["lsc-khan-ahmar-33"]: [ls3_img0, ls3_img1, ls3_img2, ls3_img3, ls3_img4, ls3_img5, ls3_img6],
  ["lsc-mohammad-ram-40"]: [ls4_img0, ls4_img1, ls4_img2, ls4_img3, ls4_img4, ls4_img5, ls4_img6, ls4_img7, ls4_img8, ls4_img9],
  ["lsc-nibal-school-46"]: [ls5_img0, ls5_img1, ls5_img2, ls5_img3, ls5_img4, ls5_img5, ls5_img6, ls5_img7, ls5_img8, ls5_img9, ls5_img10, ls5_img11],
  ["lsc-shalabi-56"]: [ls6_img0, ls6_img1, ls6_img2, ls6_img3, ls6_img4, ls6_img5, ls6_img6],
};

export function getLandscapeProjectGalleryImages(projectId: string): StaticImageData[] | undefined {
  return landscapeGalleryById[projectId];
}
