/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-landscape-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import ls0_img0 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/ODAY_result.webp";
import ls0_img1 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/1 copy_result.webp";
import ls0_img2 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/7 copy_result.webp";
import ls0_img3 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/9 copy_result.webp";
import ls0_img4 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/13 copy_result.webp";
import ls0_img5 from "@/imgs/Exterior/landscape/ali 5alaf rendering classic a3/15 copy_result.webp";
import ls1_img0 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/ODAY_result.webp";
import ls1_img1 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/1 copy_result.webp";
import ls1_img2 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/2 copy 2_result.webp";
import ls1_img3 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/2 copy_result.webp";
import ls1_img4 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/4 copy_result.webp";
import ls1_img5 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/7 copy_result.webp";
import ls1_img6 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/9 copy_result.webp";
import ls1_img7 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/15 copy_result.webp";
import ls1_img8 from "@/imgs/Exterior/landscape/ali 5alaf rendering modern aa3/17 copy_result.webp";
import ls2_img0 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/ODAY_result.webp";
import ls2_img1 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/1_result.webp";
import ls2_img2 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/4_result.webp";
import ls2_img3 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74701_result.webp";
import ls2_img4 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74702_result.webp";
import ls2_img5 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74703_result.webp";
import ls2_img6 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74704_result.webp";
import ls2_img7 from "@/imgs/Exterior/landscape/ghazi el bazzar 24/freepik__enhance__74706_result.webp";
import ls3_img0 from "@/imgs/Exterior/landscape/khan ahmar 33/oday_result.webp";
import ls3_img1 from "@/imgs/Exterior/landscape/khan ahmar 33/0.0_result.webp";
import ls3_img2 from "@/imgs/Exterior/landscape/khan ahmar 33/0.1_result.webp";
import ls3_img3 from "@/imgs/Exterior/landscape/khan ahmar 33/0.2_result.webp";
import ls3_img4 from "@/imgs/Exterior/landscape/khan ahmar 33/0.5_result.webp";
import ls3_img5 from "@/imgs/Exterior/landscape/khan ahmar 33/0.6_result.webp";
import ls3_img6 from "@/imgs/Exterior/landscape/khan ahmar 33/0.7_result.webp";
import ls4_img0 from "@/imgs/Exterior/landscape/mohammad ram 40/oday_result.webp";
import ls4_img1 from "@/imgs/Exterior/landscape/mohammad ram 40/1 copy_result.webp";
import ls4_img2 from "@/imgs/Exterior/landscape/mohammad ram 40/2 copy_result.webp";
import ls4_img3 from "@/imgs/Exterior/landscape/mohammad ram 40/3 copy_result.webp";
import ls4_img4 from "@/imgs/Exterior/landscape/mohammad ram 40/5 copy_result.webp";
import ls4_img5 from "@/imgs/Exterior/landscape/mohammad ram 40/6 copy_result.webp";
import ls4_img6 from "@/imgs/Exterior/landscape/mohammad ram 40/7 copy_result.webp";
import ls4_img7 from "@/imgs/Exterior/landscape/mohammad ram 40/11 copy_result.webp";
import ls4_img8 from "@/imgs/Exterior/landscape/mohammad ram 40/12 copy_result.webp";
import ls4_img9 from "@/imgs/Exterior/landscape/mohammad ram 40/13 copy_result.webp";
import ls5_img0 from "@/imgs/Exterior/landscape/nibal school 46/oday_result.webp";
import ls5_img1 from "@/imgs/Exterior/landscape/nibal school 46/250414 Nibal school-Model copy_result.webp";
import ls5_img2 from "@/imgs/Exterior/landscape/nibal school 46/250414 Nibal school-Model11_result.webp";
import ls5_img3 from "@/imgs/Exterior/landscape/nibal school 46/ديتليز_result.webp";
import ls5_img4 from "@/imgs/Exterior/landscape/nibal school 46/consept copy_result.webp";
import ls5_img5 from "@/imgs/Exterior/landscape/nibal school 46/D1+ copy_result.webp";
import ls5_img6 from "@/imgs/Exterior/landscape/nibal school 46/ISO1 copy_result.webp";
import ls5_img7 from "@/imgs/Exterior/landscape/nibal school 46/LAYER copy_result.webp";
import ls5_img8 from "@/imgs/Exterior/landscape/nibal school 46/poster 2_result.webp";
import ls5_img9 from "@/imgs/Exterior/landscape/nibal school 46/shot 1 copy_result.webp";
import ls5_img10 from "@/imgs/Exterior/landscape/nibal school 46/shot 2 copy_result.webp";
import ls5_img11 from "@/imgs/Exterior/landscape/nibal school 46/shot 4 copy_result.webp";
import ls6_img0 from "@/imgs/Exterior/landscape/shalabi 56/oday_result.webp";
import ls6_img1 from "@/imgs/Exterior/landscape/shalabi 56/A2_result.webp";
import ls6_img2 from "@/imgs/Exterior/landscape/shalabi 56/A3_result.webp";
import ls6_img3 from "@/imgs/Exterior/landscape/shalabi 56/A4_result.webp";
import ls6_img4 from "@/imgs/Exterior/landscape/shalabi 56/A5_result.webp";
import ls6_img5 from "@/imgs/Exterior/landscape/shalabi 56/A6_result.webp";
import ls6_img6 from "@/imgs/Exterior/landscape/shalabi 56/A8_result.webp";

export const landscapeProjects = [
  {
    id: "lsc-ali-5alaf-rendering-classic-a3",
    orderLabel: "01",
    title: "KHALAF",
    country: "Ramallah, Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    projectType: "Landscape Design",
    year: "2023",
    area: "120 m²",
    concept: "A refined landscape design centered around a circular outdoor pavilion that serves as a welcoming social space. The layout combines geometric pathways, carefully arranged planting beds, lawn areas, and private seating zones to create a balanced and elegant outdoor environment connected to the surrounding residence.",
    styleMaterials: "Classical contemporary style with white rendered walls, ornamental columns, a circular pergola, warm wood ceiling finishes, natural stone paving, white concrete stepping slabs, timber and metal fencing, decorative gates, manicured planting, and integrated landscape lighting.",
    image: ls0_img0,
    imageAlt: "KHALAF — design visualization",
  },
  {
    id: "lsc-ali-5alaf-rendering-modern-aa3",
    orderLabel: "02",
    title: "KHALAF",
    country: "Ramallah, Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    projectType: "Landscape Design",
    year: "2023",
    area: "120 m²",
    concept: "A contemporary landscape design centered around a sheltered outdoor living pavilion. The layout combines geometric pathways, a manicured lawn, planted borders, and comfortable seating areas to create a private and welcoming garden that extends the living spaces into the outdoors.",
    styleMaterials: "Contemporary style with a dark metal pergola, warm wood slats, large concrete stepping slabs, white rendered boundary walls, timber and metal fencing, ornamental planting, lawn areas, and integrated outdoor lighting.",
    image: ls1_img0,
    imageAlt: "KHALAF — design visualization",
  },
  {
    id: "lsc-ghazi-el-bazzar-24",
    orderLabel: "03",
    title: "AL-BAZZAR",
    country: "Ramallah, Palestine",
    tag: "Booth's",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    projectType: "Booth's",
    year: "2026",
    area: "35 m²",
    concept: "A vibrant collection of modular commercial booths designed to create an engaging pedestrian destination for food, beverage, and retail activities. The project combines compact service units with rooftop terraces, outdoor seating, and landscaped public areas, encouraging social interaction and extending the customer experience beyond the booth interiors.",
    styleMaterials: "Contemporary commercial style with bold yellow, red, and blue façades, rounded corners, black metal frames, large service openings, glass railings, rooftop pergolas, outdoor umbrellas, colorful signage, concrete paving, and integrated landscape planting.",
    image: ls2_img0,
    imageAlt: "AL-BAZZAR — design visualization",
  },
  {
    id: "lsc-khan-ahmar-33",
    orderLabel: "04",
    title: "Khan Al-Ahmar School",
    country: "Khan Al-Ahmar, Jericho, Palestine",
    tag: "School Design Competition",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    projectType: "School Design Competition",
    year: "2023",
    area: "500 m²",
    concept: "A community-oriented school designed to respond to the desert environment and the educational needs of the local community. The proposal organizes classrooms and shared facilities around shaded courtyards, with covered walkways, a central gathering space, and an integrated sports field that supports learning, play, and community activities.",
    styleMaterials: "Climate-responsive contemporary style using lightweight school buildings, shaded bamboo or reed canopies, simple pitched roofs, natural and earthy finishes, photovoltaic panels, landscaped courtyards, recycled-tire seating elements, and durable sports-surface materials.",
    image: ls3_img0,
    imageAlt: "Khan Al-Ahmar School — design visualization",
  },
  {
    id: "lsc-mohammad-ram-40",
    orderLabel: "05",
    title: "MOE",
    country: "Al Ram, Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    projectType: "Landscape Design",
    year: "2021",
    area: "140 m²",
    concept: "A formal residential landscape design organized around a sequence of landscaped courtyards, shaded walkways, and outdoor seating areas. The layout creates a welcoming transition from the street to the residence while balancing privacy, greenery, circulation, and comfortable spaces for outdoor living.",
    styleMaterials: "Classical contemporary style with white rendered boundary walls, decorative columns, traditional cornices, black metal gates and railings, light stone paving, geometric planting beds, manicured lawns, ornamental trees, potted plants, and warm outdoor lighting.",
    image: ls4_img0,
    imageAlt: "MOE — design visualization",
  },
  {
    id: "lsc-nibal-school-46",
    orderLabel: "06",
    title: "Nepal School",
    country: "Nepal",
    tag: "School Design Competition · Semi-Finalist",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    projectType: "School Design Competition · Semi-Finalist",
    year: "2024",
    area: "820 m²",
    concept: "A community-oriented school campus organized as a collection of small learning pavilions around a central courtyard. The design integrates classrooms, play areas, sports facilities, gardens, and shaded circulation spaces to create an engaging and inclusive learning environment that encourages interaction, exploration, and outdoor education.",
    styleMaterials: "Colorful contemporary style with exposed brick walls, vibrant painted façades, pitched metal roofs, timber roof structures, colorful louvered shutters, concrete columns, covered walkways, planted courtyards, murals, and playful outdoor elements.",
    image: ls5_img0,
    imageAlt: "Nepal School — design visualization",
  },
  {
    id: "lsc-shalabi-56",
    orderLabel: "07",
    title: "LANDSCAPE",
    country: "Ramallah, Palestine",
    tag: "Landscape Design",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "landscape" as const,
    projectType: "Landscape Design",
    year: "2018",
    area: "350 m²",
    concept: "A refined residential landscape design organized around a sequence of outdoor living spaces, water features, and lush planting areas. The design creates a tranquil garden experience through a curved pedestrian path, layered planting beds, a swimming pool, shaded seating, and carefully framed views toward the residence.",
    styleMaterials: "Classical contemporary style with natural stone retaining walls, white rendered planters, light stone paving, blue mosaic pool finishes, timber pergolas, ornamental shrubs, palms, flowering plants, manicured lawns, and integrated water features.",
    image: ls6_img0,
    imageAlt: "LANDSCAPE — design visualization",
  },
];

const landscapeGalleryById: Record<string, StaticImageData[]> = {
  ["lsc-ali-5alaf-rendering-classic-a3"]: [ls0_img0, ls0_img1, ls0_img2, ls0_img3, ls0_img4, ls0_img5],
  ["lsc-ali-5alaf-rendering-modern-aa3"]: [ls1_img0, ls1_img1, ls1_img2, ls1_img3, ls1_img4, ls1_img5, ls1_img6, ls1_img7, ls1_img8],
  ["lsc-ghazi-el-bazzar-24"]: [ls2_img0, ls2_img1, ls2_img2, ls2_img3, ls2_img4, ls2_img5, ls2_img6, ls2_img7],
  ["lsc-khan-ahmar-33"]: [ls3_img0, ls3_img1, ls3_img2, ls3_img3, ls3_img4, ls3_img5, ls3_img6],
  ["lsc-mohammad-ram-40"]: [ls4_img0, ls4_img1, ls4_img2, ls4_img3, ls4_img4, ls4_img5, ls4_img6, ls4_img7, ls4_img8, ls4_img9],
  ["lsc-nibal-school-46"]: [ls5_img0, ls5_img1, ls5_img2, ls5_img3, ls5_img4, ls5_img5, ls5_img6, ls5_img7, ls5_img8, ls5_img9, ls5_img10, ls5_img11],
  ["lsc-shalabi-56"]: [ls6_img0, ls6_img1, ls6_img2, ls6_img3, ls6_img4, ls6_img5, ls6_img6],
};

export function getLandscapeProjectGalleryImages(projectId: string): StaticImageData[] | undefined {
  return landscapeGalleryById[projectId];
}
