/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

export const villaGalleryLoaders: Record<
  string,
  () => Promise<StaticImageData[]>
> = {
  "vil-abu-falah-2-option-villa-4": () => import("./generated-galleries/vil-abu-falah-2-option-villa-4").then((m) => m.images),
  "vil-baha-hamdallah-8": () => import("./generated-galleries/vil-baha-hamdallah-8").then((m) => m.images),
  "vil-dr-baha-14": () => import("./generated-galleries/vil-dr-baha-14").then((m) => m.images),
  "vil-dr-salah-villa-v-18": () => import("./generated-galleries/vil-dr-salah-villa-v-18").then((m) => m.images),
  "vil-hassan-salameh-27": () => import("./generated-galleries/vil-hassan-salameh-27").then((m) => m.images),
  "vil-nasim-shawahneh-42": () => import("./generated-galleries/vil-nasim-shawahneh-42").then((m) => m.images),
  "vil-nasser-jericho-43": () => import("./generated-galleries/vil-nasser-jericho-43").then((m) => m.images),
  "vil-sofien-fayek-57": () => import("./generated-galleries/vil-sofien-fayek-57").then((m) => m.images),
  "vil-tareq-fifil-58": () => import("./generated-galleries/vil-tareq-fifil-58").then((m) => m.images),
  "vil-villa-10-viv": () => import("./generated-galleries/vil-villa-10-viv").then((m) => m.images),
  "vil-villa-11-vi12": () => import("./generated-galleries/vil-villa-11-vi12").then((m) => m.images),
  "vil-villa-12-bh": () => import("./generated-galleries/vil-villa-12-bh").then((m) => m.images),
};
