/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-landscape-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

export const landscapeGalleryLoaders: Record<
  string,
  () => Promise<StaticImageData[]>
> = {
  "lsc-ali-5alaf-rendering-classic-a3": () => import("./generated-galleries/lsc-ali-5alaf-rendering-classic-a3").then((m) => m.images),
  "lsc-ali-5alaf-rendering-modern-aa3": () => import("./generated-galleries/lsc-ali-5alaf-rendering-modern-aa3").then((m) => m.images),
  "lsc-ghazi-el-bazzar-24": () => import("./generated-galleries/lsc-ghazi-el-bazzar-24").then((m) => m.images),
  "lsc-khan-ahmar-33": () => import("./generated-galleries/lsc-khan-ahmar-33").then((m) => m.images),
  "lsc-mohammad-ram-40": () => import("./generated-galleries/lsc-mohammad-ram-40").then((m) => m.images),
  "lsc-nibal-school-46": () => import("./generated-galleries/lsc-nibal-school-46").then((m) => m.images),
  "lsc-shalabi-56": () => import("./generated-galleries/lsc-shalabi-56").then((m) => m.images),
};
