/* eslint-disable import/order */
// AUTO-GENERATED by scripts/generate-villa-projects.mjs — do not edit by hand.
import type { StaticImageData } from "next/image";

import vil0_img0 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/ODAY_result.webp";
import vil0_img1 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/119993894_4057531554273742_2501635177429446388_n_result.webp";
import vil0_img2 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120061019_4057531184273779_5895088966008098218_n_result.webp";
import vil0_img3 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120085060_4057530944273803_3497870258245948265_n_result.webp";
import vil0_img4 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120087811_4057531874273710_3885943795715893720_n_result.webp";
import vil0_img5 from "@/imgs/Exterior/Villa/abu falah 2 option villa 4/120153580_4057531694273728_2443758749108819940_n_result.webp";
import vil1_img0 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/ODAY_result.webp";
import vil1_img1 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/3 copy_result.webp";
import vil1_img2 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/6 copy_result.webp";
import vil1_img3 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/7 copy_result.webp";
import vil1_img4 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/8 copy_result.webp";
import vil1_img5 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/10 copy_result.webp";
import vil1_img6 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/11 copy_result.webp";
import vil1_img7 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/12 copy_result.webp";
import vil1_img8 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/13 copy_result.webp";
import vil1_img9 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/14 copy_result.webp";
import vil1_img10 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/15 copy_result.webp";
import vil1_img11 from "@/imgs/Exterior/Villa/BAHA HAMDALLAH 8/17 copy_result.webp";
import vil2_img0 from "@/imgs/Exterior/Villa/dr baha 14/ODAY_result.webp";
import vil2_img1 from "@/imgs/Exterior/Villa/dr baha 14/11_result.webp";
import vil2_img2 from "@/imgs/Exterior/Villa/dr baha 14/12_result.webp";
import vil2_img3 from "@/imgs/Exterior/Villa/dr baha 14/13_result.webp";
import vil2_img4 from "@/imgs/Exterior/Villa/dr baha 14/a11_result.webp";
import vil2_img5 from "@/imgs/Exterior/Villa/dr baha 14/a12_result.webp";
import vil2_img6 from "@/imgs/Exterior/Villa/dr baha 14/a13_result.webp";
import vil3_img0 from "@/imgs/Exterior/Villa/dr salah villa V 18/ODAY_result.webp";
import vil3_img1 from "@/imgs/Exterior/Villa/dr salah villa V 18/a5_result.webp";
import vil3_img2 from "@/imgs/Exterior/Villa/dr salah villa V 18/a15_result.webp";
import vil3_img3 from "@/imgs/Exterior/Villa/dr salah villa V 18/b4_result.webp";
import vil3_img4 from "@/imgs/Exterior/Villa/dr salah villa V 18/b7_result.webp";
import vil4_img0 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/ODAY_result.webp";
import vil4_img1 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/8 copy_result.webp";
import vil4_img2 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/9 copy_result.webp";
import vil4_img3 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/10 copy_result.webp";
import vil4_img4 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/11 copy_result.webp";
import vil4_img5 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/12 copy_result.webp";
import vil4_img6 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/13 copy_result.webp";
import vil4_img7 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/14 copy_result.webp";
import vil4_img8 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/15 copy_result.webp";
import vil4_img9 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/17 copy_result.webp";
import vil4_img10 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/18 copy_result.webp";
import vil4_img11 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/19 copy_result.webp";
import vil4_img12 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/20 copy (1)_result.webp";
import vil4_img13 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/21 copy_result.webp";
import vil4_img14 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/23 copy_result.webp";
import vil4_img15 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/24 copy_result.webp";
import vil4_img16 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/25 copy_result.webp";
import vil4_img17 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/26 copy_result.webp";
import vil4_img18 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/27 copy_result.webp";
import vil4_img19 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/30 copy_result.webp";
import vil4_img20 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/31 copy_result.webp";
import vil4_img21 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/32 copy_result.webp";
import vil4_img22 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/33 copy_result.webp";
import vil4_img23 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/35 copy_result.webp";
import vil4_img24 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/36 copy_result.webp";
import vil4_img25 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/37 copy_result.webp";
import vil4_img26 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/38 copy_result.webp";
import vil4_img27 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/39 copy_result.webp";
import vil4_img28 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/40 copy_result.webp";
import vil4_img29 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/41 copy_result.webp";
import vil4_img30 from "@/imgs/Exterior/Villa/hASSAN SALAMEH 27/42 copy_result.webp";
import vil5_img0 from "@/imgs/Exterior/Villa/nasim shawahneh 42/oday_result.webp";
import vil5_img1 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33170_result.webp";
import vil5_img2 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33180_result.webp";
import vil5_img3 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33181_result.webp";
import vil5_img4 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__-__33183_result.webp";
import vil5_img5 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__4622_result.webp";
import vil5_img6 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33165_result.webp";
import vil5_img7 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33168_result.webp";
import vil5_img8 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33172_result.webp";
import vil5_img9 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33175_result.webp";
import vil5_img10 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__33177_result.webp";
import vil5_img11 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__71855_result.webp";
import vil5_img12 from "@/imgs/Exterior/Villa/nasim shawahneh 42/freepik__enhance__99477_result.webp";
import vil6_img0 from "@/imgs/Exterior/Villa/nasser jericho 43/oday_result.webp";
import vil6_img1 from "@/imgs/Exterior/Villa/nasser jericho 43/1_result.webp";
import vil6_img2 from "@/imgs/Exterior/Villa/nasser jericho 43/2_result.webp";
import vil6_img3 from "@/imgs/Exterior/Villa/nasser jericho 43/3_result.webp";
import vil6_img4 from "@/imgs/Exterior/Villa/nasser jericho 43/4_result.webp";
import vil6_img5 from "@/imgs/Exterior/Villa/nasser jericho 43/5_result.webp";
import vil6_img6 from "@/imgs/Exterior/Villa/nasser jericho 43/7_result.webp";
import vil6_img7 from "@/imgs/Exterior/Villa/nasser jericho 43/9_result.webp";
import vil6_img8 from "@/imgs/Exterior/Villa/nasser jericho 43/10_result.webp";
import vil6_img9 from "@/imgs/Exterior/Villa/nasser jericho 43/12_result.webp";
import vil6_img10 from "@/imgs/Exterior/Villa/nasser jericho 43/13_result.webp";
import vil7_img0 from "@/imgs/Exterior/Villa/sofien fayek 57/oday_result.webp";
import vil7_img1 from "@/imgs/Exterior/Villa/sofien fayek 57/2_result.webp";
import vil7_img2 from "@/imgs/Exterior/Villa/sofien fayek 57/3_result.webp";
import vil7_img3 from "@/imgs/Exterior/Villa/sofien fayek 57/4_result.webp";
import vil7_img4 from "@/imgs/Exterior/Villa/sofien fayek 57/5_result.webp";
import vil7_img5 from "@/imgs/Exterior/Villa/sofien fayek 57/6_result.webp";
import vil7_img6 from "@/imgs/Exterior/Villa/sofien fayek 57/10_result.webp";
import vil7_img7 from "@/imgs/Exterior/Villa/sofien fayek 57/11_result.webp";
import vil8_img0 from "@/imgs/Exterior/Villa/tareq fifil 58/oday_result.webp";
import vil8_img1 from "@/imgs/Exterior/Villa/tareq fifil 58/1_result.webp";
import vil8_img2 from "@/imgs/Exterior/Villa/tareq fifil 58/2_result.webp";
import vil8_img3 from "@/imgs/Exterior/Villa/tareq fifil 58/3_result.webp";
import vil8_img4 from "@/imgs/Exterior/Villa/tareq fifil 58/4_result.webp";
import vil8_img5 from "@/imgs/Exterior/Villa/tareq fifil 58/5_result.webp";
import vil8_img6 from "@/imgs/Exterior/Villa/tareq fifil 58/6_result.webp";
import vil8_img7 from "@/imgs/Exterior/Villa/tareq fifil 58/7_result.webp";
import vil8_img8 from "@/imgs/Exterior/Villa/tareq fifil 58/8_result.webp";
import vil8_img9 from "@/imgs/Exterior/Villa/tareq fifil 58/9_result.webp";
import vil8_img10 from "@/imgs/Exterior/Villa/tareq fifil 58/13_result.webp";
import vil8_img11 from "@/imgs/Exterior/Villa/tareq fifil 58/14_result.webp";
import vil8_img12 from "@/imgs/Exterior/Villa/tareq fifil 58/16_result.webp";
import vil8_img13 from "@/imgs/Exterior/Villa/tareq fifil 58/17_result.webp";
import vil9_img0 from "@/imgs/Exterior/Villa/villa 10 viv/ODAY_result.webp";
import vil9_img1 from "@/imgs/Exterior/Villa/villa 10 viv/1_result.webp";
import vil9_img2 from "@/imgs/Exterior/Villa/villa 10 viv/2_result.webp";
import vil9_img3 from "@/imgs/Exterior/Villa/villa 10 viv/3_result.webp";
import vil9_img4 from "@/imgs/Exterior/Villa/villa 10 viv/4_result.webp";
import vil9_img5 from "@/imgs/Exterior/Villa/villa 10 viv/5_result.webp";
import vil10_img0 from "@/imgs/Exterior/Villa/villa 11 vi12/ODAY_result.webp";
import vil10_img1 from "@/imgs/Exterior/Villa/villa 11 vi12/1_result.webp";
import vil10_img2 from "@/imgs/Exterior/Villa/villa 11 vi12/2_result.webp";
import vil10_img3 from "@/imgs/Exterior/Villa/villa 11 vi12/3_result.webp";
import vil10_img4 from "@/imgs/Exterior/Villa/villa 11 vi12/4_result.webp";
import vil11_img0 from "@/imgs/Exterior/Villa/villa 12 bh/ODAY_result.webp";
import vil11_img1 from "@/imgs/Exterior/Villa/villa 12 bh/1_result.webp";
import vil11_img2 from "@/imgs/Exterior/Villa/villa 12 bh/2_result.webp";
import vil11_img3 from "@/imgs/Exterior/Villa/villa 12 bh/3_result.webp";
import vil11_img4 from "@/imgs/Exterior/Villa/villa 12 bh/4_result.webp";
import vil11_img5 from "@/imgs/Exterior/Villa/villa 12 bh/5_result.webp";
import vil11_img6 from "@/imgs/Exterior/Villa/villa 12 bh/6_result.webp";
import vil11_img7 from "@/imgs/Exterior/Villa/villa 12 bh/7_result.webp";
import vil11_img8 from "@/imgs/Exterior/Villa/villa 12 bh/8_result.webp";

export const villaProjects = [
  {
    id: "vil-abu-falah-2-option-villa-4",
    orderLabel: "01",
    title: "Villa R.H",
    country: "Ramallah, Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Residential Villa",
    year: "2018",
    area: "650 m²",
    concept: "A spacious family villa designed around generous terraces, layered outdoor spaces, and strong indoor–outdoor connections. The design combines formal architectural details with a comfortable contemporary lifestyle.",
    styleMaterials: "Contemporary classical style with white stone façades, dark metal railings, large windows, wooden pergolas, and light-colored paving.",
    image: vil0_img0,
    imageAlt: "Villa R.H — exterior visualization",
  },
  {
    id: "vil-baha-hamdallah-8",
    orderLabel: "02",
    title: "B.H 1 Villa",
    country: "Ramallah, Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Residential Villa",
    year: "2023",
    area: "630 m²",
    concept: "A contemporary villa designed with strong geometric forms, carefully framed openings, and a clear connection between the indoor and outdoor spaces. The layered volumes and integrated lighting create a refined and welcoming residential environment.",
    styleMaterials: "Contemporary minimalist style with concrete surfaces, dark textured façades, light stone or plaster finishes, black metal details, glass openings, and warm architectural lighting.",
    image: vil1_img0,
    imageAlt: "B.H 1 Villa — exterior visualization",
  },
  {
    id: "vil-dr-baha-14",
    orderLabel: "03",
    title: "DR BAHA Villa",
    country: "Ramallah, Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Residential Villa",
    year: "2020",
    area: "420 m²",
    concept: "A modern family villa designed with a balanced composition of solid volumes, spacious terraces, and generous glazed openings. The design creates a bright and welcoming living environment while maintaining privacy and a strong connection with the surrounding landscape.",
    styleMaterials: "Contemporary style with white plastered façades, dark gray accents, natural stone cladding, glass openings, metal details, and landscaped outdoor areas.",
    image: vil2_img0,
    imageAlt: "DR BAHA Villa — exterior visualization",
  },
  {
    id: "vil-dr-salah-villa-v-18",
    orderLabel: "04",
    title: "V Villa",
    country: "Ramallah, Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Residential Villa",
    year: "2021",
    area: "535 m²",
    concept: "A contemporary villa designed to respond to its sloped site through a dynamic arrangement of terraces, balconies, and open outdoor spaces. The design creates a strong connection with the surrounding landscape while offering privacy, natural light, and comfortable living spaces.",
    styleMaterials: "Contemporary minimalist style with white plastered façades, natural stone retaining walls, dark metal railings, wooden ceiling details, large glass openings, and warm integrated lighting.",
    image: vil3_img0,
    imageAlt: "V Villa — exterior visualization",
  },
  {
    id: "vil-hassan-salameh-27",
    orderLabel: "05",
    title: "HOUSE OF SUN",
    country: "Ramallah, Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Residential Villa",
    year: "2022",
    area: "680 m²",
    concept: "A distinctive villa inspired by Mediterranean architectural principles, designed around a sequence of courtyards, terraces, and outdoor living spaces. The composition emphasizes privacy, natural light, and a harmonious relationship between the building, landscape, and surrounding stone walls. Arched openings and soft architectural lighting create a warm and welcoming atmosphere.",
    styleMaterials: "Contemporary Mediterranean style with white plastered façades, arched openings, natural stone walls, decorative screens, curved terraces, integrated warm lighting, landscaped gardens, and carefully designed outdoor seating areas.",
    image: vil4_img0,
    imageAlt: "HOUSE OF SUN — exterior visualization",
  },
  {
    id: "vil-nasim-shawahneh-42",
    orderLabel: "06",
    title: "420 I Villa",
    country: "Jaljuliya",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Residential Villa",
    year: "2025",
    area: "395 m²",
    concept: "A contemporary villa defined by bold geometric volumes, deep recessed balconies, and a strong contrast between solid façades and open spaces. The design creates a private and welcoming residence through carefully framed views, layered terraces, and warm integrated lighting.",
    styleMaterials: "Modern minimalist style with dark gray cladding, light concrete or plastered surfaces, wood-textured wall finishes, large glass openings, black metal details, and warm architectural lighting.",
    image: vil5_img0,
    imageAlt: "420 I Villa — exterior visualization",
  },
  {
    id: "vil-nasser-jericho-43",
    orderLabel: "07",
    title: "Twins' Villas",
    country: "Jericho, Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Twins' Residential Villas",
    year: "2017",
    area: "440 m²",
    concept: "A symmetrical twin-villa project organized around a central axis and a shared landscaped entrance. The design creates two harmonious residential units with balanced proportions, curved balconies, generous outdoor spaces, and a strong sense of connection between the architecture and the surrounding landscape.",
    styleMaterials: "Contemporary style with light-colored stone or plastered façades, dark roof edges, curved glass balconies, wood accents, large glazed openings, landscaped courtyards, and carefully designed outdoor seating areas.",
    image: vil6_img0,
    imageAlt: "Twins' Villas — exterior visualization",
  },
  {
    id: "vil-sofien-fayek-57",
    orderLabel: "08",
    title: "SAHER RESIDENCE",
    country: "Ramallah, Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Residential Villa",
    year: "2018",
    area: "840 m²",
    concept: "A spacious multi-level residence designed to maximize views, natural light, and outdoor living. The building is organized through a series of terraces and balconies that create a strong connection between the interior spaces, the surrounding landscape, and the outdoor areas.",
    styleMaterials: "Contemporary classical style with white stone façades, decorative cornices, wide balconies, dark metal railings, large windows, wooden pergola details, and landscaped outdoor spaces.",
    image: vil7_img0,
    imageAlt: "SAHER RESIDENCE — exterior visualization",
  },
  {
    id: "vil-tareq-fifil-58",
    orderLabel: "09",
    title: "VILLA MODERNE",
    country: "Ramallah, Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Residential Villa",
    year: "2019",
    area: "460 m²",
    concept: "A contemporary villa organized around a private landscaped courtyard that serves as the heart of the home. The design emphasizes indoor–outdoor living through open terraces, shaded seating areas, and carefully framed views, creating a calm and comfortable residential environment.",
    styleMaterials: "Modern minimalist style with white plastered façades, clean geometric volumes, perforated decorative screens, large glass openings, concrete surfaces, wooden pergola elements, dark metal details, and landscaped gardens.",
    image: vil8_img0,
    imageAlt: "VILLA MODERNE — exterior visualization",
  },
  {
    id: "vil-villa-10-viv",
    orderLabel: "10",
    title: "V I V",
    country: "Kfar Qasim",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Residential Villa",
    year: "2025",
    area: "185 m²",
    concept: "A compact contemporary villa designed through a dynamic composition of interlocking volumes, elevated living spaces, and open terraces. The design responds to the surrounding natural setting while maximizing privacy, natural light, and functional outdoor areas. Integrated parking beneath the building and rooftop terraces enhance the efficiency of the compact site.",
    styleMaterials: "Modern minimalist style with white and charcoal-gray façades, clean geometric forms, large glazed openings, black metal railings, wooden pergola elements, textured plaster finishes, and warm integrated lighting.",
    image: vil9_img0,
    imageAlt: "V I V — exterior visualization",
  },
  {
    id: "vil-villa-11-vi12",
    orderLabel: "11",
    title: "V I 12",
    country: "Kfar Qasim",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Multi-Level Residential Villa",
    year: "2025",
    area: "460 m²",
    concept: "A contemporary multi-level villa designed through a dynamic composition of intersecting volumes, layered balconies, and strong vertical elements. The design combines privacy with openness, using generous glazing, shaded outdoor spaces, and a clearly defined relationship between the interior and exterior areas.",
    styleMaterials: "Modern minimalist style with white plastered façades, dark marble-effect cladding, warm wood accents, vertical screens, glass balcony railings, black metal details, and integrated architectural lighting.",
    image: vil10_img0,
    imageAlt: "V I 12 — exterior visualization",
  },
  {
    id: "vil-villa-12-bh",
    orderLabel: "12",
    title: "B.H Villa",
    country: "Ramallah, Palestine",
    tag: "Villa Exterior",
    category: "Residential" as const,
    serviceSlug: "exterior" as const,
    exteriorType: "villas" as const,
    projectType: "Residential Villa",
    year: "2026",
    area: "780 m²",
    concept: "A luxurious contemporary villa designed as a series of layered volumes that respond to the sloped site. The composition combines generous terraces, framed views, private outdoor spaces, and a carefully integrated water feature. Decorative screens and deep overhangs provide privacy and shade while enhancing the architectural identity of the residence.",
    styleMaterials: "Contemporary luxury style with light natural stone façades, dark textured cladding, large glass openings, geometric metal screens, glass railings, wood ceiling details, sculptural water features, landscaped terraces, and warm integrated lighting.",
    image: vil11_img0,
    imageAlt: "B.H Villa — exterior visualization",
  },
];

const villaGalleryById: Record<string, StaticImageData[]> = {
  ["vil-abu-falah-2-option-villa-4"]: [vil0_img0, vil0_img1, vil0_img2, vil0_img3, vil0_img4, vil0_img5],
  ["vil-baha-hamdallah-8"]: [vil1_img0, vil1_img1, vil1_img2, vil1_img3, vil1_img4, vil1_img5, vil1_img6, vil1_img7, vil1_img8, vil1_img9, vil1_img10, vil1_img11],
  ["vil-dr-baha-14"]: [vil2_img0, vil2_img1, vil2_img2, vil2_img3, vil2_img4, vil2_img5, vil2_img6],
  ["vil-dr-salah-villa-v-18"]: [vil3_img0, vil3_img1, vil3_img2, vil3_img3, vil3_img4],
  ["vil-hassan-salameh-27"]: [vil4_img0, vil4_img1, vil4_img2, vil4_img3, vil4_img4, vil4_img5, vil4_img6, vil4_img7, vil4_img8, vil4_img9, vil4_img10, vil4_img11, vil4_img12, vil4_img13, vil4_img14, vil4_img15, vil4_img16, vil4_img17, vil4_img18, vil4_img19, vil4_img20, vil4_img21, vil4_img22, vil4_img23, vil4_img24, vil4_img25, vil4_img26, vil4_img27, vil4_img28, vil4_img29, vil4_img30],
  ["vil-nasim-shawahneh-42"]: [vil5_img0, vil5_img1, vil5_img2, vil5_img3, vil5_img4, vil5_img5, vil5_img6, vil5_img7, vil5_img8, vil5_img9, vil5_img10, vil5_img11, vil5_img12],
  ["vil-nasser-jericho-43"]: [vil6_img0, vil6_img1, vil6_img2, vil6_img3, vil6_img4, vil6_img5, vil6_img6, vil6_img7, vil6_img8, vil6_img9, vil6_img10],
  ["vil-sofien-fayek-57"]: [vil7_img0, vil7_img1, vil7_img2, vil7_img3, vil7_img4, vil7_img5, vil7_img6, vil7_img7],
  ["vil-tareq-fifil-58"]: [vil8_img0, vil8_img1, vil8_img2, vil8_img3, vil8_img4, vil8_img5, vil8_img6, vil8_img7, vil8_img8, vil8_img9, vil8_img10, vil8_img11, vil8_img12, vil8_img13],
  ["vil-villa-10-viv"]: [vil9_img0, vil9_img1, vil9_img2, vil9_img3, vil9_img4, vil9_img5],
  ["vil-villa-11-vi12"]: [vil10_img0, vil10_img1, vil10_img2, vil10_img3, vil10_img4],
  ["vil-villa-12-bh"]: [vil11_img0, vil11_img1, vil11_img2, vil11_img3, vil11_img4, vil11_img5, vil11_img6, vil11_img7, vil11_img8],
};

export function getVillaProjectGalleryImages(projectId: string): StaticImageData[] | undefined {
  return villaGalleryById[projectId];
}
